project:
  type: website
  render:
    - "*.{qmd,R,py,md}"
    - "!archive/**/*"
  preview: 
    # host: 0.0.0.0
    port: 4200

website:
  site-url: https://pinn32.github.io
  title: "pinn.xu"
  description: "A collection of projects by Pinn (Aiqi) Xu, showcasing work in data science, machine learning, and software development."
  favicon: src/img/favicon/spark.ico

  back-to-top-navigation: true
  page-footer: 
    left: | 
      © Copyright <span id="copyright-year"></span>, Pinn (Aiqi) Xu. All rights reserved.
  
  repo-url: https://github.com/Pinn32/dv-projects
  repo-actions: [edit, source, issue]
  repo-link-target: _blank

  comments:
    giscus: 
      repo: Pinn32/pinn32.github.io

  #############################################################################
  navbar:
    left:
      # - text: Home
      #   href: index.qmd
      - text: Projects
        href: en/projects/index.qmd
      - text: Tutorials
        href: en/tutorials/index.qmd
      - text: Tools
        href: en/tools/index.qmd
      - text: Blogs
        href: en/blogs/index.qmd
      # - text: Hobbies
      #   href: en/hobbies/index.qmd
      # - text: All Posts
      #   href: en/all-posts/index.qmd
      - text: About
        href: en/about/index.qmd

    right:
      - text: Changes
        href: en/changes/index.md


    ###### NavBar Tools #################################################
    tools: 
      ###### Language Switch / Translation ######
      - icon: translate
        menu: 
          - text: English
            href: "#"
          - text: 中文
            href: "#"

      - icon: github
        href: https://github.com/Pinn32/dv-projects

      - icon: linkedin
        href: https://www.linkedin.com/in/aiqi-xu-71943b378/

      # - icon: https://cdn.brandfetch.io/idriarYq6Q/w/400/h/400/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1686028240869
      #   href: https://twitter.com/<insert_twitter_id_here>


  #############################################################################
  sidebar: 
    - id: en-sidebar
      logo: false
      search: true
      style: 'docked'
      collapse-level: 1
      contents:
        - section: "Projects"
          contents: "en/projects/*/index.*md"
        - section: "Tutorials"
          contents: "en/tutorials/*/index.*md"
        - section: "Blogs"
          contents: "en/blogs/*/index.*md"
        - section: "Tools"
          contents: "en/tools/*/index.*md"
        - text: "Reproduce This Project"
          href: "en/readme/index.md"
        - text: "Change Log"
          href: "en/changes/index.md"
        - text: "About"
          href: en/about/index.qmd
    - id: zh-sidebar
      logo: false
      search: true
      style: 'docked'
      collapse-level: 1
      contents:
        - section: "可视化项目"
          contents: "zh/projects/*/index.*md"
        - section: "数据分析教程"
          contents: "zh/tutorials/*/index.*md"
        - section: "经验博客"
          contents: "zh/blogs/*/index.*md"
        - section: "Web工具"
          contents: "zh/tools/*/index.*md"
        - text: "项目复现"
          href: "zh/readme/index.md"
        - text: "更新日志"
          href: "zh/changes/index.md"
        - text: "关于"
          href: zh/about/index.qmd


###############################################################################
format:
  html:
    # self-contained: false
    lightbox: true
    smooth-scroll: true
    syntax-highlighting: 
      light: pygments
      dark: atom-one
    respect-user-color-scheme: true
    theme:
      light: [minty, ./src/styles/portfolio.scss]
      dark:  [minty, ./src/styles/portfolio-dark.scss]
    from: markdown+mark    # enable `==mark==` syntax for highlighting text

    # external links
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:https?:\/\/)?(?:pinn32\.github\.io\/(?:en|zh|dv-projects|img)|raw\.githubusercontent\.com\/Pinn32\/img)(?:\/|$)'
    
    ###### JS Scripts ######
    include-after-body:
      - ./src/scripts/site-fixes.html        # combined global fixes & tweaks

    toc: true
    # toc-expand: true
    # toc-depth: 3
    code-tools: true
      # toggle: true
      # source: true
      # caption: "hi"
    code-fold: true
    # code-summary: "Show the code"


##############################################################################

# lang: en
brand: _brand.yml
editor: source
filters:
  - src/filters/reading-stats.lua  # for reading time
  - src/filters/changelog-timeline.lua  # change-log timeline (en/changes)