{
  "hash": "7be522b4d8105d3d69ffc01bbbfabe40",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Evolution of Online AI Discourse'\ndescription: 'A Longitudinal Analysis of Public Sentiment and Thematic Trends in AI-Related Tweets'\nauthor: 'Pinn Xu'\ndate: '2026-05-01'\n# categories: [R, AI, NLP, Text Analysis, Sentiment Analysis, Topic Modeling, Social Media]\ncategories: [R, AI, NLP, Text Analysis, Social Media]\nbibliography: references.bib\ncsl: ../../../src/apa.csl\nnumber-sections: true\naliases: \n  - ../ai-tweets/\n  - ../ai-discourse/\n\norder: 1\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-summary=\"Environment & Versions\"}\nR==4.5.2\nMASS==7.3.65\ntidyverse==2.0.0\ntidytext==0.4.3\ntextdata==0.4.5\ntopicmodels==0.2.17\nscales==1.4.0\nbroom==1.0.12\ntextutils==0.4.3\nknitr==1.51\n```\n:::\n\n\n# Introduction\n\nThe rapid development of artificial intelligence (AI) over the past few years has fundamentally transformed how technology is embedded in daily life, reshaping industries, communication practices, and public discourse [@stone2022]. As AI evolved from a niche technical field into a widely discussed social phenomenon, public opinion surrounding it has expanded significantly across digital platforms. Social media, particularly Twitter (now X), has played a central role in this transformation by providing a space where users, individual founders, and institutions actively discuss, evaluate, and negotiate the meaning and implications of AI technologies [@bruns2015]. Given this context, Twitter data offers a valuable lens for understanding how people's perception and opinions toward AI develop over time, especially during periods of rapid technology progress. Analyzing such discourse through computational social data analysis is particularly meaningful for the social science field, enabling researchers to systematically examine how technological innovation is interpreted, debated, negotiated, and culturally integrated within society.\n\nDespite growing scholarly attention to AI-related communication, relatively few studies have examined how public discourse evolves longitudinally alongside the mainstream adoption of AI tools [@cave2019]. Most existing research tends to focus on public perceptions or attitudes measured through surveys or short-term datasets [@cave2019], which limits the ability to capture dynamic shifts in attention, framing, and emotional response over time. To address this gap, this study investigates AI-related discourse on Twitter between 2017 and 2021, a period during which the application of AI tools was significantly expanded. By analyzing large-scale tweet data, this research seeks to identify how thematic structures and sentiment patterns change across time and how these changes reflect broader socio-cultural shifts.\n\nAccordingly, this study is guided by two research questions:\n\n1. How did the core themes and topics of AI-related discourse on Twitter evolve between 2017 and 2021 as the technology moved toward mainstream adoption?\n\n2. How are these identified themes and specific sentiment polarities associated with user engagement (e.g., likes, replies, and retweets)?\n\n# Data\n\n## Dataset\n\nTo address the questions, this study used a curated and anonymized dataset with large-scaled AI-related tweets collected via the Twitter API from 2017 to 2021, including metadata such as engagement metrics, hashtags, language, and temporal features, supporting research on public discourse, sentiment, and topic evolution [@demarcelliswarin2025]. The unit of analysis for this study is each individual tweet with its associated metadata.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)         # glm.nb — load before tidyverse to avoid name conflicts\nlibrary(tidyverse)    # readr, tidyr, tibble, dplyr, ggplot2, lubridate, etc.\nlibrary(tidytext)     # text analysis (tokenize)\nlibrary(textdata)     # sentiment lexicons\nlibrary(topicmodels)  # topic modeling\nlibrary(scales)       # axis scales\nlibrary(broom)        # tidy() model outputs\n\n# import dataset\ndata0 <- read_csv(\"../../../src/data/tweets_ai.csv\")\n\n# view structure\nglimpse(data0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 893,076\nColumns: 19\n$ id              <dbl> 8.265808e+17, 8.265807e+17, 8.265806e+17, 8.265806e+17…\n$ conversation_id <dbl> 8.265808e+17, 8.265807e+17, 8.265806e+17, 8.265806e+17…\n$ created_at      <chr> \"2017-01-31 18:59:44 EST\", \"2017-01-31 18:59:35 EST\", …\n$ date            <date> 2017-01-31, 2017-01-31, 2017-01-31, 2017-01-31, 2017-…\n$ time            <time> 18:59:44, 18:59:35, 18:59:14, 18:59:01, 18:59:01, 18:…\n$ timezone        <dbl> -400, -400, -400, -400, -400, -400, -400, -400, -400, …\n$ tweet           <chr> \"What topic could spark human dialogue on AI? Artifici…\n$ language        <chr> \"en\", \"en\", \"en\", \"en\", \"en\", \"en\", \"en\", \"en\", \"en\", …\n$ urls            <chr> \"['https://blog.hubspot.com/marketing/artificial-intel…\n$ photos          <chr> \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"['https://pbs.twi…\n$ replies_count   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ retweets_count  <dbl> 0, 4, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, …\n$ likes_count     <dbl> 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, …\n$ hashtags        <chr> \"[]\", \"['artificialintelligence', 'ai', 'chasmwaxing']…\n$ cashtags        <chr> \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", \"[]\", …\n$ retweet         <lgl> FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE…\n$ quote_url       <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, \"https://twitter.c…\n$ video           <dbl> 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, …\n$ thumbnail       <chr> NA, NA, NA, NA, NA, NA, \"https://pbs.twimg.com/media/C…\n```\n\n\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Original Observations:\", nrow(data0), \"\\n\")\ncat(\"Original Variables:\", length(data0), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOriginal Observations: 893076 \nOriginal Variables: 19 \n```\n\n\n:::\n:::\n\n\n## Observations\n\nTo facilitate the analysis, this study narrows down the sample size by keeping only original tweets (excluding retweets) in English, and a stratified sampling by posting year was conducted with a sample size of 3,000 in order to ensure computational efficiency while maintaining a sufficient sample size for analysis (see [Appendix](#appendix) for the narrowing process).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view language distribution\ndata0 |>\n  count(language, sort = TRUE) |>\n  head(4)\n\ncat(\"\\n\")\n\n# view originality\ndata0 |> count(retweet)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 2\n  language      n\n  <chr>     <int>\n1 en       833879\n2 fr        16259\n3 und       12504\n4 es         5557\n\n# A tibble: 1 × 2\n  retweet      n\n  <lgl>    <int>\n1 FALSE   893076\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# keep only original tweets in English\ndata <- data0 |>\n  filter(language == \"en\" & retweet == FALSE)\n\ncat(\"Observations after preprocessing:\", nrow(data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations after preprocessing: 833879 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check missing data in date column\ncat(\"Any NA in date column:\", anyNA(data$date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAny NA in date column: FALSE \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view observation counts by year\ndata |>\n  group_by(year = year(date)) |>\n  count(year)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n# Groups:   year [5]\n   year      n\n  <dbl>  <int>\n1  2017 305247\n2  2018 216067\n3  2019 204567\n4  2020  77905\n5  2021  30093\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# equal-allocation stratified random sampling by year\nN <- 3000\nst_size <- N / length(unique(year(data$date)))  # stratum size\nset.seed(32)\ndata <- data |>\n  group_by(year = year(date)) |>\n  slice_sample(n = st_size) |>\n  ungroup()\n```\n:::\n\n\n## Variables\n\nSeveral variables are included in the original dataset, such as the textual content of each tweet, metadata like time and engagement metrics, and hashtags. This diverse nature of variables enables multi-dimensional social data analysis. This study uses 7 variables stemmed from the original variables, including the textual content of tweets, hashtags, cashtags, posting date, and counts of likes, replies, and retweets (see @tbl-data-doc for detailed descriptions). Specifically, the original posting date variable was preprocessed and normalized to Coordinated Universal Time (UTC), stored in a new variable named `date_utc`. Meanwhile, the original variable for textual content of tweets was renamed to `text`.\n\n| Variable | Data Type | Description |\n|:---|:---:|:---|\n| `date_utc` | Date | Posting date of each tweet in yyyy-mm-dd format in UTC |\n| `text` | Character | Textual content of each tweet |\n| `hashtags` | Character | List of hashtags included in each tweet |\n| `cashtags` | Character | List of cashtags (e.g., stock symbols) included in each tweet |\n| `likes_count` | Numeric | Number of likes received by each tweet |\n| `replies_count` | Numeric | Number of replies received by each tweet |\n| `retweets_count` | Numeric | Number of times each tweet was retweeted |\n\n: Data Documentation Table {#tbl-data-doc tbl-colwidths=\"[18,16,66]\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# posting date info column\nstr(data[[\"created_at\"]])\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n chr [1:3000] \"2017-08-29 15:18:24 EDT\" \"2017-03-27 18:42:13 EDT\" ...\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check unique timezone suffix\ndata |>\n  mutate(suffix = str_sub(created_at, -3, -1)) |>\n  count(suffix, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  suffix     n\n  <chr>  <int>\n1 EDT     1710\n2 EST     1290\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# normalize posting date to UTC\ndata <- data |>\n  mutate(\n    created_at_ct = ymd_hms(created_at, tz = \"America/New_York\"),\n    date_utc      = date(with_tz(created_at_ct, tzone = \"UTC\"))\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# keep only variables to be used\ndata <- data |>\n  mutate(text = tweet) |>\n  select(\n    date_utc, text, hashtags, cashtags,\n    likes_count, replies_count, retweets_count\n  )\n\ncat(\"Observations Count:\", nrow(data), \"\\n\")\ncat(\"Variables Count:\", length(data), \"\\n\")\ncat(\"Any NA in data:\", anyNA(data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nObservations Count: 3000 \nVariables Count: 7 \nAny NA in data: FALSE \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [3,000 × 7] (S3: tbl_df/tbl/data.frame)\n $ date_utc      : Date[1:3000], format: \"2017-08-29\" \"2017-03-27\" ...\n $ text          : chr [1:3000] \"Brands Can’t Afford to Underestimate the Power of Artificial Intelligence, OMD’s Retail Revolution  https://t.c\"| __truncated__ \"NASA : One of our planet’s few exposed lava lakes is changing, and artificial intelligence…  https://t.co/h7Lp7\"| __truncated__ \"Artificial intelligence to be showcased in Guangzhou  - Business -  https://t.co/Qk6gmORE4m  https://t.co/NsuAj\"| __truncated__ \"Artificial Intelligence: Implications On Marketing, Analytics, And You  https://t.co/v8p1metjJE via @avinash vi\"| __truncated__ ...\n $ hashtags      : chr [1:3000] \"['ai', 'ml', 'dl']\" \"[]\" \"['ai', 'ml', 'dl']\" \"[]\" ...\n $ cashtags      : chr [1:3000] \"[]\" \"[]\" \"[]\" \"[]\" ...\n $ likes_count   : num [1:3000] 0 0 0 0 0 3 0 0 0 0 ...\n $ replies_count : num [1:3000] 0 0 0 0 0 0 0 0 0 0 ...\n $ retweets_count: num [1:3000] 0 0 0 0 1 3 1 0 0 1 ...\n```\n\n\n:::\n:::\n\n\n## Descriptive Statistics of Engagement Metrics\n\n@tbl-desc-stats shows the descriptive statistics of the numeric variables. As a supplement, @tbl-zero-counts shows the count and proportion of zero and non-zero values among these numeric variables.\n\nThe descriptive statistics across all three engagement metrics (counts of likes, replies, and retweets) show a highly skewed distribution, indicating that the majority of tweets in this dataset received no engagement. Among the metrics, likes are the most common form of interaction, with a mean of 3.04 and 40.40% of tweets receiving at least one like, followed closely by retweets at a mean of 2.35 and 41.40% non-zero values. Replies were notably rare, with only 7.07% of tweets receiving any response and a mean of just 0.14. The relatively large standard deviations, combined with the substantial gaps between the 75th percentile values (0 or 1) and the maximum values (898 likes, 83 replies, 367 retweets), suggest the presence of a small number of highly viral tweets that disproportionately inflate the averages.\n\n\n::: {#tbl-desc-stats .cell tbl-colwidths='[22,12,12,11,10,10,11,12]'}\n\n```{.r .cell-code}\nnum_vars <- c(\"likes_count\", \"replies_count\", \"retweets_count\")\n\n# compute summary statistics for each numeric variable and pivot to long format\nnum_stats_table <- data |>\n  summarise(across(\n    all_of(num_vars),\n    list(\n      mean   = ~round(mean(.x, na.rm = TRUE), 2),\n      sd     = ~round(sd(.x, na.rm = TRUE), 2),\n      min    = ~min(.x, na.rm = TRUE),\n      q1     = ~quantile(.x, 0.25, na.rm = TRUE),\n      median = ~median(.x, na.rm = TRUE),\n      q3     = ~quantile(.x, 0.75, na.rm = TRUE),\n      max    = ~max(.x, na.rm = TRUE)\n    ),\n    .names = \"{.col}###{.fn}\"\n  )) |>\n  # \"###\" is a collision-safe delimiter \n  # for splitting \"col###stat\" in pivot_longer\n  pivot_longer(\n    everything(),\n    names_to  = c(\"Variable\", \".value\"),\n    names_sep = \"###\"\n  )\n\nknitr::kable(\n  num_stats_table |>\n    rename(\n      Mean = mean, SD = sd, Min = min,\n      `25%` = q1, Median = median, `75%` = q3, Max = max\n    ),\n  align = c('l', 'c', 'c', 'c', 'c', 'c', 'c', 'c'),\n  caption = \"Descriptive Statistics Summary of Numeric Variables\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Descriptive Statistics Summary of Numeric Variables\n\n|Variable       | Mean |  SD   | Min | 25% | Median | 75% | Max |\n|:--------------|:----:|:-----:|:---:|:---:|:------:|:---:|:---:|\n|likes_count    | 3.04 | 23.28 |  0  |  0  |   0    |  1  | 898 |\n|replies_count  | 0.14 | 1.65  |  0  |  0  |   0    |  0  | 83  |\n|retweets_count | 2.35 | 11.12 |  0  |  0  |   0    |  1  | 367 |\n\n\n:::\n:::\n\n\n\n::: {#tbl-zero-counts .cell}\n\n```{.r .cell-code}\n# count zero vs non-zero values for each engagement metric\nzero_counts_table <- data |>\n  summarise(across(\n    all_of(num_vars),\n    list(\n      zero         = ~sum(.x == 0, na.rm = TRUE),\n      non_zero     = ~sum(.x > 0, na.rm = TRUE),\n      pct_non_zero = ~round(sum(.x > 0, na.rm = TRUE) / n() * 100, 2)\n    ),\n    .names = \"{.col}###{.fn}\"\n  )) |>\n  pivot_longer(\n    everything(),\n    names_to  = c(\"Variable\", \".value\"),\n    names_sep = \"###\"\n  )\n\nknitr::kable(\n  zero_counts_table |>\n    rename(\n      `Count of Zero Values`    = zero,\n      `Count of Non-zero Values`= non_zero,\n      `Proportion of Non-zero Values (%)` = pct_non_zero\n    ),\n  caption = \"Zero and Non-zero Values of Numeric Variables\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Zero and Non-zero Values of Numeric Variables\n\n|Variable       | Count of Zero Values| Count of Non-zero Values| Proportion of Non-zero Values (%)|\n|:--------------|--------------------:|------------------------:|---------------------------------:|\n|likes_count    |                 1787|                     1213|                             40.43|\n|replies_count  |                 2788|                      212|                              7.07|\n|retweets_count |                 1759|                     1241|                             41.37|\n\n\n:::\n:::\n\n\n## Date Variable\n\nThe date variable involved in this study is `date_utc`, derived from the original `created_at` variable and normalized to UTC (see [Appendix](#appendix) for the conversion process). It ranges from January 27th, 2017, to July 19th, 2021, covering a total time span of 5 years (1,634 days).\n\nThe unit of analysis over time in this study is each day. @fig-daily-dist shows the daily distribution of tweets, where the x-axis displays the time range of the dataset (January 27th, 2017, to July 19th, 2021) and the y-axis represents the counts of observed tweets by day. Overall, tweet volume remained relatively low and stable in the earlier years of the dataset, generally fluctuating between 0 and 20 tweets per day, before showing a notable increase in activity around 2020–2021, with several prominent spikes, including one approaching 100 tweets in a single day, suggesting a growing public interest in AI-related discourse toward the end of the observation period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Date Range (yyyy-mm-dd):\\n\",\n    as.character(range(data$date_utc)[1]), \"to\",\n    as.character(range(data$date_utc)[2]), \"\\n\")\nmax(data$date_utc) - min(data$date_utc)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDate Range (yyyy-mm-dd):\n 2017-01-27 to 2021-07-19 \nTime difference of 1634 days\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndaily_count <- data |>\n  count(date_utc)\n\nmin_date <- min(daily_count$date_utc)\nmax_date <- max(daily_count$date_utc)\n# include both endpoints explicitly \n# so the axis always shows actual start/end dates\nx_breaks <- sort(unique(c(min_date, seq(min_date, max_date, by = \"9 months\"), max_date)))\n\nggplot(daily_count, aes(x = date_utc, y = n)) +\n  geom_area(fill = \"rosybrown\", alpha = 0.7) +\n  scale_x_date(breaks = x_breaks, date_labels = \"%m-%d-%Y\") +\n  labs(\n    title = \"Daily Distribution of AI-Related Tweets (2017–2021)\",\n    x = \"Timeline (Daily Unit of Analysis)\",\n    y = \"Number of Tweets\"\n  ) +\n  theme_minimal() +\n  theme(\n    axis.text.x  = element_text(angle = 45, hjust = 1, size = 8),\n    axis.title.x = element_text(margin = margin(t = 10)),\n    axis.title.y = element_text(margin = margin(r = 10)),\n    panel.grid.minor = element_blank(),\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Daily Distribution of AI-Related Tweets (2017–2021)](index_files/figure-html/fig-daily-dist-1.png){#fig-daily-dist width=768}\n:::\n:::\n\n\n## Text Variables\n\nThere are three textual variables involved in this study: `text`, `hashtags`, and `cashtags`.\n\n### Text\n\nThe `text` variable contains the unique textual content of each tweet, with no missing values (NAs) nor empty content (empty string `\"\"`), with a sample size of 3,000. The number of unique values in the `text` variable is 2,995. For example, `\"Brands Can't Afford to Underestimate the Power of Artificial Intelligence, OMD's Retail Revolution https://t.co/l1hSywqKgM #ai #ml #dl\"` is one of the values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Number of Empty Tweets:\", sum(data$text == \"\"), \"\\n\")\ncat(\"Number of Unique Tweets:\", length(unique(data$text)), \"\\n\\n\")\ncat(\"First 6 Unique Tweets:\\n\")\nhead(unique(data$text))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Empty Tweets: 0 \nNumber of Unique Tweets: 2995 \n\nFirst 6 Unique Tweets:\n[1] \"Brands Can’t Afford to Underestimate the Power of Artificial Intelligence, OMD’s Retail Revolution  https://t.co/l1hSywqKgM #ai #ml #dl\"                    \n[2] \"NASA : One of our planet’s few exposed lava lakes is changing, and artificial intelligence…  https://t.co/h7Lp70dYlv)  https://t.co/JFljeXzLE0\"             \n[3] \"Artificial intelligence to be showcased in Guangzhou  - Business -  https://t.co/Qk6gmORE4m  https://t.co/NsuAjIJiAo #ai #ml #dl\"                           \n[4] \"Artificial Intelligence: Implications On Marketing, Analytics, And You  https://t.co/v8p1metjJE via @avinash via @avinash  https://t.co/SojmDRiXk6\"         \n[5] \"#ArtificialIntelligence #AI Automation high on employers' agenda as skills gaps set to bite - CIPD (blog)  https://t.co/mtAfFTvA16  https://t.co/SNKDxkSUeT\"\n[6] \"Surden on Values Embedded in Legal Artificial Intelligence @HarrySurden  https://t.co/vBkBoWU1Nz\"                                                           \n```\n\n\n:::\n:::\n\n\n### Hashtags\n\nThe `hashtags` is another textual variable. It contains lists of lowercase hashtags starting with the `#` symbol in each tweet (all hashtags from the original tweets were converted to lowercase), with no missing values (NAs). Specifically, it contains 2,059 non-empty values (i.e., 2,059 observations contain one or more hashtags), where there are 1,539 non-empty unique values (excluding `\"[]\"`). For instance, `\"['ai', 'ml', 'dl']\"` and `\"['artificialintelligence', 'ai']\"` are two of the values.\n\nIn addition, as each tweet can contain multiple hashtags, the values are separated into single hashtags to gain more nuanced insights (see [Appendix](#appendix) for the separation process). As observed, there are 2,382 non-empty unique single hashtags. For example, `\"ai\"` and `\"ml\"` are two of the unique single hashtags.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count non-empty and unique hashtag values\nunique_hashtags <- data |>\n  filter(hashtags != \"[]\") |>\n  select(hashtags) |>\n  count(hashtags)\n\ncat(\"Number of Non-empty Hashtags:\", sum(data$hashtags != \"[]\"), \"\\n\")\ncat(\"Number of Unique Non-empty Hashtags:\", nrow(unique_hashtags), \"\\n\\n\")\ncat(\"First 6 Unique Hashtags:\\n\")\nhead(unique(data$hashtags))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Non-empty Hashtags: 2059 \nNumber of Unique Non-empty Hashtags: 1539 \n\nFirst 6 Unique Hashtags:\n[1] \"['ai', 'ml', 'dl']\"                                  \n[2] \"[]\"                                                  \n[3] \"['artificialintelligence', 'ai']\"                    \n[4] \"['summer', 'artificialintelligence', 'ai']\"          \n[5] \"['artificialintelligence', 'ai', 'nlp', 'ecommerce']\"\n[6] \"['ai']\"                                              \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find unique single hashtags\nsingle_hashtags <- data |>\n  mutate(single_hashtags = str_remove_all(hashtags, \"[\\\\[\\\\]']\")) |>\n  separate_rows(single_hashtags, sep = \",\\\\s*\") |>\n  filter(single_hashtags != \"\") |>\n  count(single_hashtags)\n\ncat(\"Number of Non-empty Unique Single Hashtags:\", nrow(single_hashtags), \"\\n\\n\")\ncat(\"First 6 Non-empty Unique Single Hashtags:\\n\")\nhead(unique(single_hashtags$single_hashtags))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Non-empty Unique Single Hashtags: 2382 \n\nFirst 6 Non-empty Unique Single Hashtags:\n[1] \"004nino\"         \"100daysofcod\"    \"100daysofcode\"   \"100daysofmlcode\"\n[5] \"10xgrowth\"       \"1trendstoday\"   \n```\n\n\n:::\n:::\n\n\n### Cashtags\n\nLikewise, the `cashtags` variable contains lists of lowercase cashtags in each tweet, which are clickable financial ticker symbols on Twitter (now X), formed by prefixing a stock or cryptocurrency abbreviation with the `$` sign. There are no missing values (NAs), 22 non-empty values (i.e., 22 observations contain one or more cashtags), and 18 non-empty unique values. For example, `\"['aieq', 'bikr']\"` and `\"['blk']\"` are two of the values. Additionally, there are 23 non-empty unique single cashtags in total, such as `\"ark\"`, `\"blk\"`, and `\"btc\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# count non-empty and unique cashtag values\nunique_cashtags <- data |>\n  filter(cashtags != \"[]\") |>\n  select(cashtags) |>\n  count(cashtags)\n\ncat(\"Number of Non-empty Cashtags:\", sum(data$cashtags != \"[]\"), \"\\n\")\ncat(\"Number of Non-empty Unique Cashtags:\", nrow(unique_cashtags), \"\\n\\n\")\ncat(\"First 6 Unique Cashtags:\\n\")\nhead(unique(data$cashtags))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Non-empty Cashtags: 22 \nNumber of Non-empty Unique Cashtags: 18 \n\nFirst 6 Unique Cashtags:\n[1] \"[]\"               \"['v']\"            \"['blk']\"          \"['infy']\"        \n[5] \"['aieq', 'bikr']\" \"['qlys']\"        \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# strip list formatting and split into one row per cashtag\nsingle_cashtags <- data |>\n  mutate(single_cashtags = str_remove_all(cashtags, \"[\\\\[\\\\]']\")) |>\n  separate_rows(single_cashtags, sep = \",\\\\s*\") |>\n  filter(single_cashtags != \"\") |>\n  count(single_cashtags)\n\ncat(\"Number of Non-empty Unique Single Cashtags:\", nrow(single_cashtags), \"\\n\\n\")\ncat(\"Head of Non-empty Unique Single Cashtags:\\n\")\nhead(unique(single_cashtags$single_cashtags))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of Non-empty Unique Single Cashtags: 23 \n\nHead of Non-empty Unique Single Cashtags:\n[1] \"aieq\" \"ark\"  \"axxa\" \"bikr\" \"blk\"  \"btc\" \n```\n\n\n:::\n:::\n\n\n## Text Preparation\n\nText cleaning and tokenization are performed as a preprocessing step for subsequent analyses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# text cleaning\ndata <- data |>\n  mutate(textBU = text) |>           # back up raw text before cleaning\n  filter(!is.na(text)) |>\n  mutate(\n    text = textutils::HTMLdecode(text),           # decode HTML entities (e.g., &amp;)\n    text = str_to_lower(text),                    # normalize to lowercase\n    text = str_remove_all(text, \"https?://\\\\S+\"), # strip URLs\n    text = str_remove_all(text, \"\\\\d+\"),          # strip digits\n    text = str_remove_all(text, \"[@]\\\\w+\"),       # strip @mentions\n    text = str_squish(text)                        # collapse extra whitespace\n  ) |>\n  mutate(\n    tweet_index = row_number(),           # sequential ID for joining\n    nwords      = str_count(text, \"\\\\w+\") # word count after cleaning\n  )\n\nhead(data$text)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"brands can’t afford to underestimate the power of artificial intelligence, omd’s retail revolution #ai #ml #dl\"\n[2] \"nasa : one of our planet’s few exposed lava lakes is changing, and artificial intelligence…\"                   \n[3] \"artificial intelligence to be showcased in guangzhou - business - #ai #ml #dl\"                                 \n[4] \"artificial intelligence: implications on marketing, analytics, and you via via\"                                \n[5] \"#artificialintelligence #ai automation high on employers' agenda as skills gaps set to bite - cipd (blog)\"     \n[6] \"surden on values embedded in legal artificial intelligence\"                                                    \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tokenize hashtags\nhashtag_tokens <- data |>\n  select(tweet_index, date_utc, hashtags) |>\n  mutate(hashtag = str_remove_all(hashtags, \"[\\\\[\\\\]']\")) |>\n  separate_rows(hashtag, sep = \",\\\\s*\") |>\n  filter(hashtag != \"\")\n\n# tokenize cashtags\ncashtag_tokens <- data |>\n  select(tweet_index, date_utc, cashtags) |>\n  mutate(cashtag = str_remove_all(cashtags, \"[\\\\[\\\\]']\")) |>\n  separate_rows(cashtag, sep = \",\\\\s*\") |>\n  filter(cashtag != \"\")\n\n# tweet-level tag features\ntag_features <- data |>\n  select(tweet_index, date_utc, likes_count, replies_count, retweets_count) |>\n  left_join(\n    hashtag_tokens |> count(tweet_index, name = \"n_hashtag\"),\n    by = \"tweet_index\"\n  ) |>\n  left_join(\n    cashtag_tokens |> count(tweet_index, name = \"n_cashtag\"),\n    by = \"tweet_index\"\n  ) |>\n  mutate(\n    n_hashtag   = replace_na(n_hashtag, 0L),\n    n_cashtag   = replace_na(n_cashtag, 0L),\n    has_hashtag = n_hashtag > 0,\n    has_cashtag = n_cashtag > 0,\n    year        = year(date_utc)\n  )\n\ntag_features |>\n  select(tweet_index, n_hashtag, n_cashtag, has_hashtag, has_cashtag) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 5\n  tweet_index n_hashtag n_cashtag has_hashtag has_cashtag\n        <int>     <int>     <int> <lgl>       <lgl>      \n1           1         3         0 TRUE        FALSE      \n2           2         0         0 FALSE       FALSE      \n3           3         3         0 TRUE        FALSE      \n4           4         0         0 FALSE       FALSE      \n5           5         2         0 TRUE        FALSE      \n6           6         0         0 FALSE       FALSE      \n```\n\n\n:::\n:::\n\n\n# Methods\n\n## Statistical Methods\n\nPrior to model estimation, correlation analysis is conducted as an exploratory step to examine the pairwise relationships between thematic features, sentiment scores, and user engagement metrics. This preliminary analysis helps identify potential associations and informs the selection of variables for subsequent modeling, while also providing an initial understanding of the direction and strength of relationships within the dataset.\n\nIn the meantime, this paper employs Generalized Linear Models (GLMs) to generate models to examine the relationship between variables. GLMs were chosen over simple linear regression due to the nature of the engagement data containing a preponderance of zero values, which is a distributional characteristic that standard linear models may not adequately handle. By accommodating non-normal response distributions, GLMs offer a more flexible and appropriate modeling approach for count-based social media engagement data.\n\n## Text-as-Data Methods\n\nFor text analysis, this paper draws on two complementary computational techniques. Latent Dirichlet Allocation (LDA) topic modeling, which is a widely used unsupervised machine learning technique, is applied to uncover potential thematic structures within the dataset, identifying the core subjects that characterized AI-related discourse. Meanwhile, sentiment analysis with lexicons, a natural language processing approach evaluating the emotional tone of textual data by leveraging predefined lexical resources to classify polarity (e.g., positive, negative, or neutral), is also employed to establish the overall emotional polarity and trends among tweets. In addition, Term Frequency-Inverse Document Frequency (TF-IDF) is used to track how the salience of key AI-related terms shifted from 2017 to 2021, offering a longitudinal perspective on lexical change as AI moved toward mainstream adoption.\n\nThese methods directly support the research questions investigating how identified themes and sentiments polarities are associated with user engagement, as Topic Modeling and Sentiment Analysis allow the study to identify underlying themes and sentiments, while TF-IDF provides a temporal perspective on the evolving trends of AI-related key terms across the dataset. Together, these techniques inform the subsequent inferential analysis, in which GLM provide insights into the predictive relationships between textual variables and engagement metrics statistically.\n\n# Results\n\n## LDA Topic Modeling\n\nTo identify the underlying thematic structure of AI-related tweets, LDA was applied to the preprocessed tweet corpus. After tokenization, tweets were filtered using a custom stopword list that removed general English stopwords, Twitter-specific terms (e.g., `\"rt\"`, `\"tweet\"`), and the search keyword `\"artificial intelligence\"`. A TF-IDF filter then retained only words appearing in more than 0.1% but fewer than 75% of all documents, reducing vocabulary noise while preserving informative terms. The resulting document-term matrix served as input to the LDA model, which was estimated with K = 5 topics using Gibbs sampling with 2,000 iterations and a 500-iteration burn-in period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# custom domain-specific stopwords\nmystopwords <- c(\n  stop_words$word,\n  \"comment\", \"post\",\n  \"twitter\", \"tweet\", \"tweets\",\n  \"rt\", \"retweet\", \"retweets\",\n  \"artificial\", \"intelligence\"\n)\nmystopwords <- tolower(unique(mystopwords))\ncat(\"Total stopwords:\", length(mystopwords), \"\\n\")\n\n# tokenize\ntm_token_data <- data |>\n  unnest_tokens(word, text) |>\n  anti_join(data.frame(word = mystopwords)) |>\n  mutate(nchar = nchar(word)) |>\n  filter(nchar > 2) |>\n  filter(!grepl(\"[0-9]{1}\", word)) |>\n  filter(!grepl(\"\\\\W\", word))\n\ncat(\"Total tokens:\", nrow(tm_token_data), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal stopwords: 738 \nTotal tokens: 27565 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_docs_total <- n_distinct(tm_token_data$tweet_index)\n\n# retain words in (0.1%, 75%) document frequency range\ngood_words <- tm_token_data |>\n  count(tweet_index, word) |>\n  group_by(word) |>\n  summarise(doc_freq = n() / n_docs_total, .groups = \"drop\") |>\n  filter(doc_freq < 0.75, doc_freq > 0.001)\n\ntm_token_data_pruned <- tm_token_data |>\n  inner_join(good_words, by = \"word\")\n\ncat(\"Vocabulary after TF-IDF filter:\", nrow(good_words), \"words\\n\")\ncat(\"Tokens after filter:\", nrow(tm_token_data_pruned), \"\\n\")\n\n# document-term matrix\ntweet_dtm <- tm_token_data_pruned |>\n  count(tweet_index, word) |>\n  cast_dtm(tweet_index, word, n)\n\ncat(\"DTM:\", nrow(tweet_dtm), \"documents x\", ncol(tweet_dtm), \"terms\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVocabulary after TF-IDF filter: 1800 words\nTokens after filter: 20112 \nDTM: 2961 documents x 1800 terms\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(32)\nlda_model <- LDA(\n  tweet_dtm, k = 5, method = \"Gibbs\",\n  control = list(seed = 32, iter = 2000, burnin = 500, verbose = 0)\n)\n# persist to disk so the object survives \n# chunk-cache invalidation and is usable externally\nsave(lda_model, file = \"./lda_model_ai.RData\")\n```\n:::\n\n\n@fig-lda-words displays the top 10 words by probability (beta) for each of the five topics, providing the basis for thematic interpretation. Based on the word distributions, the topics were labeled as follows: Topic 1 represents robotics and automation, with key terms such as *robotics*, *automation*, and *robot*; Topic 2 reflects technology, research, and financial markets, featuring words like *blockchain*, *technology*, *research*, *market*, and *healthcare*; Topic 3 captures data science, machine learning, and security, with terms including *data*, *learning*, *machine*, and *security*; Topic 4 represents business-oriented AI innovation, characterized by words like *business*, *future*, *innovation*, *digital*, and *digitaltransformation*; and Topic 5 emphasizes applied AI ecosystem vocabulary, including *machinelearning*, *bigdata*, *datascience*, *iot*, and *deeplearning*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlda_beta <- tidy(lda_model, matrix = \"beta\")\n\nlda_beta |>\n  group_by(topic) |>\n  slice_max(beta, n = 10) |>\n  ungroup() |>\n  mutate(term = reorder_within(term, beta, topic)) |>\n  ggplot(aes(beta, term, fill = factor(topic))) +\n  geom_col(show.legend = FALSE) +\n  facet_wrap(~topic, scales = \"free\") +\n  scale_y_reordered() +\n  labs(\n    title = \"Top 10 Words per LDA Topic (K = 5)\",\n    x = \"Beta (Word Probability)\", \n    y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Top 10 Words per LDA Topic (K = 5)<br>\n*Note.* Bars represent word probability (beta) within each topic. Topics are labeled by their dominant semantic cluster.](index_files/figure-html/fig-lda-words-1.png){#fig-lda-words width=768}\n:::\n:::\n\n\n@tbl-topic-dist presents the distribution of dominant topics, which is the topic with the highest membership probability for each tweet, across the 3,000 sampled tweets. Topic 1 (robotics and automation) was the most prevalent, accounting for 28.4% of tweets, followed by Topic 2 (technology and markets, 23.3%), Topic 3 (data science and security, 19.0%), Topic 4 (business and innovation, 15.3%), and Topic 5 (AI ecosystem buzzwords, 14.0%). The distribution was moderately uneven, with Topics 1 and 2 together covering more than half of all tweets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# gamma matrix: document-topic probabilities\nlda_gamma <- tidy(lda_model, matrix = \"gamma\")\n\n# reshape wide and join with original data\ngamma_wide <- lda_gamma |>\n  mutate(tweet_index = as.integer(document)) |>\n  select(-document) |>\n  pivot_wider(names_from = topic, values_from = gamma, names_prefix = \"topic_\")\n\nmeta_theta_df <- data |>\n  inner_join(gamma_wide, by = \"tweet_index\")\n```\n:::\n\n\n\n::: {#tbl-topic-dist .cell tbl-colwidths='[20,40,40]'}\n\n```{.r .cell-code}\n# assign each tweet its dominant topic (highest gamma) and tabulate counts\ndominant_dist <- lda_gamma |>\n  group_by(document) |>\n  slice_max(gamma, n = 1) |>\n  ungroup() |>\n  count(topic) |>\n  mutate(pct = round(n / sum(n) * 100, 1))\n\nknitr::kable(\n  dominant_dist |>\n    rename(\n      Topic = topic,\n      `Tweet Count` = n,\n      `Percentage (%)` = pct\n    ),\n  align = c('c','c','c'),\n  caption = \"Distribution of Dominant LDA Topics Across Tweets\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Distribution of Dominant LDA Topics Across Tweets\n\n| Topic | Tweet Count | Percentage (%) |\n|:-----:|:-----------:|:--------------:|\n|   1   |     865     |      20.7      |\n|   2   |     779     |      18.7      |\n|   3   |     837     |      20.1      |\n|   4   |     833     |      20.0      |\n|   5   |     855     |      20.5      |\n\n\n:::\n:::\n\n\n@fig-topic-over-time traces average topic probabilities (gamma) across years from 2017 to 2021. Notably, all five topics maintained average probabilities close to 0.20 throughout the study period, indicating a relatively stable thematic structure over time. Despite this overall stability, subtle directional shifts were present. Topic 4 (business and innovation) showed a modest upward trend from 2017 to 2021, while Topic 2 (technology and markets) declined slightly. Topic 5 (AI ecosystem buzzwords) also edged upward by 2021. These patterns suggest that while the broad thematic balance of AI discourse remained intact, business- and implementation-oriented language gradually gained somewhat greater prominence as AI moved toward mainstream adoption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute mean topic probability (gamma) per year for trend visualization\ntopics_by_year <- lda_gamma |>\n  mutate(tweet_index = as.integer(document)) |>\n  left_join(data |> select(tweet_index, date_utc), by = \"tweet_index\") |>\n  mutate(year = year(date_utc)) |>\n  group_by(year, topic) |>\n  summarise(mean_gamma = mean(gamma), .groups = \"drop\")\n\nggplot(topics_by_year, aes(x = year, y = mean_gamma, color = factor(topic))) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2.5) +\n  scale_x_continuous(breaks = 2017:2021) +\n  scale_color_manual(\n    values = c(\n      \"1\" = \"coral\", \"2\" = \"darkgoldenrod3\", \"3\" = \"darkseagreen\",\n      \"4\" = \"steelblue\", \"5\" = \"orchid3\"\n    ),\n    labels = paste(\"Topic\", 1:5)\n  ) +\n  labs(\n    title = \"Topic Prevalence Over Time (2017–2021)\",\n    x = \"Year\", \n    y = \"Average Topic Probability (Gamma)\", \n    color = \"Topic\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Topic Prevalence Over Time (2017–2021)<br>\n*Note.* Lines represent mean gamma (topic membership probability) across all tweets in each year. All five topics remain close to 0.20 throughout the period, indicating thematic stability.](index_files/figure-html/fig-topic-over-time-1.png){#fig-topic-over-time width=768}\n:::\n:::\n\n\n## Hashtag and Cashtag Analysis\n\nHashtag and cashtag analysis complemented the topic model by examining the explicit user-generated labels that framed AI-related tweets. @tbl-tag-presence summarizes the overall prevalence of hashtags and cashtags. Among the 3,000 sampled tweets, 2,059 (68.6%) contained at least one hashtag, with an average of 3.45 hashtags per tweet. By contrast, only 22 tweets (0.7%) contained any cashtag, with an average of just 0.01 per tweet. This large difference in frequency suggests that financial and market-oriented labeling through cashtags was marginal in this corpus, while hashtag use was both widespread and dense.\n\n\n::: {#tbl-tag-presence .cell tbl-colwidths='[19,27,27,27]'}\n\n```{.r .cell-code}\n# summarize hashtag and cashtag prevalence across the sample\ntag_presence_table <- tibble(\n  tag_type = c(\"Hashtag\", \"Cashtag\"),\n  tweets_with_tag = c(\n    sum(tag_features$has_hashtag), sum(tag_features$has_cashtag)\n  ),\n  pct_with_tag    = round(tweets_with_tag / nrow(tag_features) * 100, 1),\n  avg_tags_per_tweet = c(\n    round(mean(tag_features$n_hashtag), 2),\n    round(mean(tag_features$n_cashtag), 2)\n  )\n)\n\nknitr::kable(\n  tag_presence_table |>\n    rename(\n      `Tag Type`              = tag_type,\n      `Tweets With Tag`       = tweets_with_tag,\n      `Percent of Tweets (%)` = pct_with_tag,\n      `Avg. Tags per Tweet`   = avg_tags_per_tweet\n    ),\n  align = 'c',\n  caption = \"Prevalence of Hashtags and Cashtags in the Sample\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Prevalence of Hashtags and Cashtags in the Sample\n\n| Tag Type | Tweets With Tag | Percent of Tweets (%) | Avg. Tags per Tweet |\n|:--------:|:---------------:|:---------------------:|:-------------------:|\n| Hashtag  |      2059       |         68.6          |        3.45         |\n| Cashtag  |       22        |          0.7          |        0.01         |\n\n\n:::\n:::\n\n\n@tbl-top-hashtags and @fig-top-hashtags display the 15 most frequently used hashtags across the full 2017–2021 sample. The top three were #artificialintelligence (1,427 uses), #ai (1,094 uses), and #machinelearning (483 uses), followed by #bigdata, #datascience, #deeplearning, #iot, and #ml. This ranking indicates that AI tweets were predominantly framed through technical and industry labels rather than through social, ethical, or political categories.\n\n\n::: {#tbl-top-hashtags .cell tbl-colwidths='[50,50]'}\n\n```{.r .cell-code}\n# count and rank all single hashtags; keep top 15\ntop_hashtags <- hashtag_tokens |>\n  count(hashtag, sort = TRUE) |>\n  slice_max(n, n = 15)\n\nknitr::kable(\n  top_hashtags |> rename(Hashtag = hashtag, Frequency = n),\n  align = 'c',\n  caption = \"Most Frequent Hashtags in AI-Related Tweets (2017–2021)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Most Frequent Hashtags in AI-Related Tweets (2017–2021)\n\n|        Hashtag         | Frequency |\n|:----------------------:|:---------:|\n| artificialintelligence |   1427    |\n|           ai           |   1094    |\n|    machinelearning     |    483    |\n|        bigdata         |    230    |\n|      datascience       |    229    |\n|      deeplearning      |    218    |\n|          iot           |    189    |\n|           ml           |    184    |\n|       technology       |    166    |\n|          tech          |    111    |\n|        robotics        |    99     |\n|       analytics        |    88     |\n|       blockchain       |    85     |\n|       innovation       |    76     |\n|       automation       |    75     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# horizontal bar chart of the 15 most frequent hashtags\ntop_hashtags |>\n  mutate(hashtag = reorder(hashtag, n)) |>\n  ggplot(aes(x = n, y = hashtag)) +\n  geom_col(fill = \"darkcyan\", alpha = 0.8) +\n  labs(\n    title = \"Top 15 Hashtags in AI-Related Tweets\",\n    x = \"Frequency\", y = NULL\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Top 15 Hashtags in AI-Related Tweets<br>\n*Note.* Bars show overall frequency across the 2017–2021 sample. Broad AI labels (#artificialintelligence, #ai) dominate, followed by applied technical subfield terms.](index_files/figure-html/fig-top-hashtags-1.png){#fig-top-hashtags width=768}\n:::\n:::\n\n\n@tbl-hashtag-by-year presents the top five hashtags by year. #artificialintelligence and #ai remained the top two in every year from 2017 to 2021. However, the third through fifth positions shifted over time: in 2017 and 2018, #bigdata and #iot appeared prominently, while by 2020 and 2021, #datascience and #deeplearning replaced them. The count of #machinelearning grew steadily, from 47 uses in 2017 to 127 in 2021. @fig-hashtag-trends shows the share trends for the eight most commonly used hashtags, visually confirming the persistence of general AI labels alongside the rising prominence of applied technical subfields.\n\n\n::: {#tbl-hashtag-by-year .cell tbl-colwidths='[30,40,30]'}\n\n```{.r .cell-code}\n# count hashtags per year and keep the top 5 per year\ntop_hashtags_year <- hashtag_tokens |>\n  mutate(year = year(date_utc)) |>\n  count(year, hashtag, sort = TRUE) |>\n  group_by(year) |>\n  slice_max(n, n = 5, with_ties = FALSE) |>\n  ungroup()\n\nknitr::kable(\n  top_hashtags_year |> rename(Year = year, Hashtag = hashtag, Frequency = n),\n  align = 'c',\n  caption = \"Top Five Hashtags by Year (2017–2021)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top Five Hashtags by Year (2017–2021)\n\n| Year |        Hashtag         | Frequency |\n|:----:|:----------------------:|:---------:|\n| 2017 | artificialintelligence |    226    |\n| 2017 |           ai           |    214    |\n| 2017 |    machinelearning     |    47     |\n| 2017 |        bigdata         |    38     |\n| 2017 |          iot           |    34     |\n| 2018 | artificialintelligence |    231    |\n| 2018 |           ai           |    215    |\n| 2018 |    machinelearning     |    76     |\n| 2018 |        bigdata         |    49     |\n| 2018 |          iot           |    43     |\n| 2019 | artificialintelligence |    316    |\n| 2019 |           ai           |    229    |\n| 2019 |    machinelearning     |    120    |\n| 2019 |        bigdata         |    53     |\n| 2019 |      datascience       |    52     |\n| 2020 | artificialintelligence |    335    |\n| 2020 |           ai           |    217    |\n| 2020 |    machinelearning     |    113    |\n| 2020 |      datascience       |    61     |\n| 2020 |      deeplearning      |    50     |\n| 2021 | artificialintelligence |    319    |\n| 2021 |           ai           |    219    |\n| 2021 |    machinelearning     |    127    |\n| 2021 |      datascience       |    77     |\n| 2021 |      deeplearning      |    64     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# identify the 8 most common hashtags overall\nfocus_hashtags <- hashtag_tokens |>\n  count(hashtag, sort = TRUE) |>\n  slice_max(n, n = 8, with_ties = FALSE) |>\n  pull(hashtag)\n\n# compute each hashtag's share of uses within each year\nhashtag_trends <- hashtag_tokens |>\n  mutate(year = year(date_utc)) |>\n  filter(hashtag %in% focus_hashtags) |>\n  count(year, hashtag) |>\n  group_by(year) |>\n  mutate(pct_year = n / sum(n)) |>\n  ungroup()\n\nggplot(hashtag_trends, aes(x = year, y = pct_year, color = hashtag)) +\n  geom_line(linewidth = 1) +\n  geom_point(size = 2) +\n  scale_x_continuous(breaks = 2017:2021) +\n  scale_y_continuous(labels = percent_format(accuracy = 1)) +\n  labs(\n    title = \"Top Hashtag Shares by Year\",\n    x = \"Year\", \n    y = \"Share of Hashtag Uses\", \n    color = \"Hashtag\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Top Hashtag Shares by Year<br>\n*Note.* Lines show each hashtag's share among the eight most common hashtags in each year. General AI labels maintain dominance while technical subfield terms gradually increase.](index_files/figure-html/fig-hashtag-trends-1.png){#fig-hashtag-trends width=768}\n:::\n:::\n\n\n@tbl-top-cashtags presents the most frequently used cashtags. The top cashtags were $btc (4 uses), $btcusd (3 uses), and $v (3 uses), with nearly all others appearing only once. The very low frequency of cashtags indicates that market- and investment-oriented discourse about AI occupied a very small niche in this corpus, and cashtags are better understood as occasional markers of crypto- or finance-adjacent AI talk rather than a major framing device.\n\n\n::: {#tbl-top-cashtags .cell}\n\n```{.r .cell-code}\n# count and rank cashtag frequency; keep top 5\ntop_cashtags <- cashtag_tokens |>\n  count(cashtag, sort = TRUE) |>\n  slice_max(n, n = 5)\n\nknitr::kable(\n  top_cashtags |> rename(Cashtag = cashtag, Frequency = n),\n  align = 'c',\n  caption = \"Most Frequent Cashtags in AI-Related Tweets (2017–2021)\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Most Frequent Cashtags in AI-Related Tweets (2017–2021)\n\n| Cashtag | Frequency |\n|:-------:|:---------:|\n|   btc   |     4     |\n| btcusd  |     3     |\n|    v    |     3     |\n|  aieq   |     1     |\n|   ark   |     1     |\n|  axxa   |     1     |\n|  bikr   |     1     |\n|   blk   |     1     |\n|   eth   |     1     |\n|  fcac   |     1     |\n|  goog   |     1     |\n|  gtch   |     1     |\n|   icr   |     1     |\n|  infy   |     1     |\n|  ipod   |     1     |\n|  ipof   |     1     |\n|   jar   |     1     |\n|  mark   |     1     |\n|  phun   |     1     |\n|  qlys   |     1     |\n|  svfau  |     1     |\n|   vrx   |     1     |\n|  vsby   |     1     |\n\n\n:::\n:::\n\n\n## Sentiment Analysis\n\n### Comparison of Sentiment Lexicons\n\nSentiment analysis was conducted using three established dictionary lexicons: AFINN, Bing, and NRC. @tbl-lexicon-coverage summarizes their coverage in the dataset. NRC achieved the broadest coverage at 90.0% of tweets scored, followed by Bing at 78.6%, and AFINN at 42.5%. @fig-lexicon-coverage displays these differences visually. Despite its lower coverage, AFINN was selected as the primary sentiment measure for three reasons. First, AFINN provides a continuous intensity scale (–5 to +5) that captures the degree of positive or negative sentiment, making it directly suitable for regression modeling. Second, among the 1,130 tweets scored by all three lexicons, AFINN correlated strongly with Bing (r = .664) and moderately with NRC (r = .510), while Bing and NRC correlated at r = .528, confirming that all three measures captured a consistent underlying signal. Third, the additional tweets scored by NRC did not justify the increased interpretive complexity of a categorical emotion framework for the purposes of this analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tokenize and remove stopwords for sentiment analysis\nsa_token_data <- data |>\n  unnest_tokens(word, text) |>\n  anti_join(stop_words, by = \"word\") |>\n  mutate(nchar_w = nchar(word))\n\ncat(\"Total tokens:\", nrow(sa_token_data), \"\\n\")\ncat(\"Unique tokens:\", n_distinct(sa_token_data$word), \"\\n\")\ncat(\"Avg tokens per tweet:\",\n    round(nrow(sa_token_data) / n_distinct(sa_token_data$tweet_index), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal tokens: 34076 \nUnique tokens: 8236 \nAvg tokens per tweet: 11.4 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# AFINN: numeric scores from -5 (very negative) to +5 (very positive)\nafinn_scores <- sa_token_data |>\n  inner_join(get_sentiments(\"afinn\"), by = \"word\") |>\n  group_by(tweet_index) |>\n  summarise(\n    sentiment_afinn = sum(value),\n    n_afinn_words   = n(),\n    avg_afinn       = mean(value),\n    .groups = \"drop\"\n  )\n\nafinn_coverage     <- nrow(afinn_scores)\nafinn_coverage_pct <- round(afinn_coverage / nrow(data) * 100, 1)\ncat(\"AFINN coverage:\", afinn_coverage, \"tweets (\", afinn_coverage_pct, \"% )\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAFINN coverage: 1275 tweets ( 42.5 % )\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bing: binary positive / negative classification\nbing_scores <- sa_token_data |>\n  inner_join(get_sentiments(\"bing\"), by = \"word\") |>\n  group_by(tweet_index) |>\n  summarise(\n    n_positive     = sum(sentiment == \"positive\"),\n    n_negative     = sum(sentiment == \"negative\"),\n    n_bing_words   = n(),\n    sentiment_bing = n_positive - n_negative,\n    .groups = \"drop\"\n  )\n\nbing_coverage     <- nrow(bing_scores)\nbing_coverage_pct <- round(bing_coverage / nrow(data) * 100, 1)\ncat(\"Bing coverage:\", bing_coverage, \"tweets (\", bing_coverage_pct, \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBing coverage: 2359 tweets ( 78.6 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NRC: 8 basic emotions + positive / negative\nnrc_raw <- sa_token_data |>\n  inner_join(get_sentiments(\"nrc\"), by = \"word\")\n\nnrc_scores <- nrc_raw |>\n  group_by(tweet_index, sentiment) |>\n  summarise(n = n(), .groups = \"drop\") |>\n  pivot_wider(names_from = sentiment, values_from = n, values_fill = 0) |>\n  mutate(sentiment_nrc = positive - negative)\n\nnrc_coverage     <- nrow(nrc_scores)\nnrc_coverage_pct <- round(nrc_coverage / nrow(data) * 100, 1)\ncat(\"NRC coverage:\", nrc_coverage, \"tweets (\", nrc_coverage_pct, \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNRC coverage: 2700 tweets ( 90 %)\n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-lexicon-coverage .cell}\n\n```{.r .cell-code}\n# assemble pre-computed coverage counts into a comparison table\ncoverage_df <- data.frame(\n  lexicon       = c(\"AFINN\", \"Bing\", \"NRC\"),\n  tweets_scored = c(afinn_coverage, bing_coverage, nrc_coverage),\n  coverage_pct  = c(afinn_coverage_pct, bing_coverage_pct, nrc_coverage_pct)\n)\n\nknitr::kable(\n  coverage_df |>\n    rename(\n      Lexicon         = lexicon,\n      `Tweets Scored` = tweets_scored,\n      `Coverage (%)`  = coverage_pct\n    ),\n  align = 'c',\n  caption = \"Coverage of Sentiment Lexicons Across the Tweet Sample\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Coverage of Sentiment Lexicons Across the Tweet Sample\n\n| Lexicon | Tweets Scored | Coverage (%) |\n|:-------:|:-------------:|:------------:|\n|  AFINN  |     1275      |     42.5     |\n|  Bing   |     2359      |     78.6     |\n|   NRC   |     2700      |     90.0     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bar chart comparing tweet coverage (%) across the three lexicons\nggplot(coverage_df, aes(x = lexicon, y = coverage_pct, fill = lexicon)) +\n  geom_col(alpha = 0.8) +\n  geom_text(aes(label = paste0(coverage_pct, \"%\")), vjust = -0.4, size = 4) +\n  ylim(0, 100) +\n  labs(\n    title = \"Sentiment Lexicon Coverage Comparison\",\n    x = NULL, \n    y = \"Coverage (%)\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Sentiment Lexicon Coverage Comparison<br>\n*Note.* Bars represent the percentage of the 3,000 tweets that received a sentiment score from each lexicon. NRC achieves the widest coverage; AFINN covers a smaller share but provides continuous intensity scores.](index_files/figure-html/fig-lexicon-coverage-1.png){#fig-lexicon-coverage width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# correlations among tweets scored by all three lexicons\nsentiment_cmp <- data |>\n  select(tweet_index) |>\n  left_join(afinn_scores |> select(tweet_index, sentiment_afinn), by = \"tweet_index\") |>\n  left_join(bing_scores  |> select(tweet_index, sentiment_bing),  by = \"tweet_index\") |>\n  left_join(nrc_scores   |> select(tweet_index, sentiment_nrc),   by = \"tweet_index\")\n\ncomplete_cmp <- sentiment_cmp |>\n  filter(!is.na(sentiment_afinn), !is.na(sentiment_bing), !is.na(sentiment_nrc))\n\ncat(\"Tweets scored by all three lexicons:\", nrow(complete_cmp), \"\\n\")\ncat(\"AFINN vs Bing: r =\",\n    round(cor(complete_cmp$sentiment_afinn, complete_cmp$sentiment_bing), 3), \"\\n\")\ncat(\"AFINN vs NRC:  r =\",\n    round(cor(complete_cmp$sentiment_afinn, complete_cmp$sentiment_nrc), 3), \"\\n\")\ncat(\"Bing  vs NRC:  r =\",\n    round(cor(complete_cmp$sentiment_bing,  complete_cmp$sentiment_nrc), 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTweets scored by all three lexicons: 1130 \nAFINN vs Bing: r = 0.665 \nAFINN vs NRC:  r = 0.509 \nBing  vs NRC:  r = 0.529 \n```\n\n\n:::\n:::\n\n\n### Temporal Trends in Sentiment\n\nAmong the 1,275 tweets that received AFINN scores, overall sentiment in the corpus was slightly positive (M = 0.81, Median = 1, range: -18 to 12). @tbl-sentiment-by-year and @fig-sentiment-by-year present mean AFINN scores by year with 95% confidence intervals. A clear upward trend is visible: mean sentiment increased from 0.33 in 2017 to 0.60 in 2018, 0.80 in 2019, 1.05 in 2020, and 1.11 in 2021. The 95% confidence intervals indicate that this upward movement became increasingly stable in later years. This pattern is consistent with the growing normalization of AI as a practical and promising technology, where public discourse shifted toward greater optimism about AI's applications and societal benefits.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# attach AFINN scores to data and propagate to meta_theta_df\ndata <- data |>\n  left_join(afinn_scores |> select(tweet_index, sentiment_afinn), by = \"tweet_index\") |>\n  mutate(sentiment_norm = sentiment_afinn / nwords)\n\nmeta_theta_df <- meta_theta_df |>\n  left_join(afinn_scores |> select(tweet_index, sentiment_afinn), by = \"tweet_index\")\n\nn_scored <- sum(!is.na(data$sentiment_afinn))\ncat(\"Tweets with AFINN scores:\", n_scored,\n    paste0(\"(\", round(n_scored / nrow(data) * 100, 1), \"%)\"), \"\\n\")\nsummary(data$sentiment_afinn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTweets with AFINN scores: 1275 (42.5%) \n    Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA's \n-18.0000  -1.0000   1.0000   0.8071   2.0000  12.0000     1725 \n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-sentiment-by-year .cell tbl-colwidths='[17,15,15,15,15,15]'}\n\n```{.r .cell-code}\n# yearly mean AFINN scores with standard errors and 95% CIs\nsentiment_by_year <- data |>\n  filter(!is.na(sentiment_afinn)) |>\n  mutate(year = year(date_utc)) |>\n  group_by(year) |>\n  summarise(\n    n         = n(),\n    mean_sent = mean(sentiment_afinn),\n    se_sent   = sd(sentiment_afinn) / sqrt(n),\n    .groups   = \"drop\"\n  ) |>\n  mutate(\n    ci_low  = mean_sent - 1.96 * se_sent,\n    ci_high = mean_sent + 1.96 * se_sent\n  )\n\nknitr::kable(\n  sentiment_by_year |>\n    rename(\n      Year = year, `Tweets Scored` = n, `Mean Sentiment` = mean_sent,\n      SE = se_sent, `95% CI Low` = ci_low, `95% CI High` = ci_high\n    ),\n  align = 'c',\n  caption = \"Mean AFINN Sentiment Score by Year with 95% Confidence Intervals\",\n  digits  = 3\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Mean AFINN Sentiment Score by Year with 95% Confidence Intervals\n\n| Year | Tweets Scored | Mean Sentiment |  SE   | 95% CI Low | 95% CI High |\n|:----:|:-------------:|:--------------:|:-----:|:----------:|:-----------:|\n| 2017 |      192      |     0.328      | 0.159 |   0.017    |    0.640    |\n| 2018 |      252      |     0.595      | 0.152 |   0.297    |    0.894    |\n| 2019 |      278      |     0.799      | 0.163 |   0.479    |    1.118    |\n| 2020 |      282      |     1.050      | 0.151 |   0.754    |    1.345    |\n| 2021 |      271      |     1.100      | 0.177 |   0.753    |    1.446    |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# line + confidence ribbon showing mean AFINN sentiment trend from 2017 to 2021\nggplot(sentiment_by_year, aes(x = year, y = mean_sent)) +\n  geom_ribbon(aes(ymin = ci_low, ymax = ci_high), alpha = 0.2, fill = \"steelblue\") +\n  geom_line(color = \"steelblue\", linewidth = 1) +\n  geom_point(color = \"steelblue\", size = 3) +\n  geom_hline(yintercept = 0, linetype = \"dotted\", color = \"red\") +\n  scale_x_continuous(breaks = 2017:2021) +\n  labs(\n    title = \"Mean AFINN Sentiment by Year (2017–2021)\",\n    x = \"Year\", \n    y = \"Mean AFINN Sentiment Score\"\n  ) +\n  theme_minimal() +\n  theme(\n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Mean AFINN Sentiment by Year (2017–2021)<br>\n*Note.* Points and line show yearly means; the ribbon represents the 95% confidence interval. The dashed horizontal line marks a score of zero (neutral). Sentiment increased consistently from 2017 to 2021.](index_files/figure-html/fig-sentiment-by-year-1.png){#fig-sentiment-by-year width=768}\n:::\n:::\n\n\n### Topic–Sentiment Relationship\n\nTo examine whether discourse topics were associated with different emotional tones, average AFINN sentiment was computed for each topic using gamma-weighted scores, where each tweet's contribution to a topic's average sentiment was proportional to its membership probability in that topic. @fig-topic-sentiment presents these weighted averages. Sentiment scores were very similar across all five topics, ranging from 0.79 (Topic 5, AI ecosystem buzzwords) to 0.84 (Topic 4, business and innovation). A weighted linear regression model predicting sentiment from topic membership found no statistically significant differences relative to Topic 1 for any other topic (all p > .80). This result shows that in this corpus, emotional tone did not vary meaningfully across thematic clusters; rather, sentiment varied more consistently over time than across topics.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute weighted sentiment per topic\nmeta_theta_df <- meta_theta_df |>\n  filter(!is.na(sentiment_afinn)) |>\n  mutate(\n    wt_sent_t1 = sentiment_afinn * topic_1,\n    wt_sent_t2 = sentiment_afinn * topic_2,\n    wt_sent_t3 = sentiment_afinn * topic_3,\n    wt_sent_t4 = sentiment_afinn * topic_4,\n    wt_sent_t5 = sentiment_afinn * topic_5\n  )\n\ntopic_sent_avg <- tibble(\n  topic = 1:5,\n  total_weighted = c(\n    sum(meta_theta_df$wt_sent_t1), sum(meta_theta_df$wt_sent_t2),\n    sum(meta_theta_df$wt_sent_t3), sum(meta_theta_df$wt_sent_t4),\n    sum(meta_theta_df$wt_sent_t5)\n  ),\n  gamma_mass = c(\n    sum(meta_theta_df$topic_1), sum(meta_theta_df$topic_2),\n    sum(meta_theta_df$topic_3), sum(meta_theta_df$topic_4),\n    sum(meta_theta_df$topic_5)\n  )\n) |>\n  mutate(\n    avg_sentiment = total_weighted / gamma_mass,\n    topic_label   = paste(\"Topic\", topic)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# horizontal bar chart of gamma-weighted average AFINN sentiment per topic\nggplot(\n  topic_sent_avg,\n  aes(x = reorder(topic_label, avg_sentiment), y = avg_sentiment, fill = topic_label)\n) +\n  geom_col(alpha = 0.8) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"red\") +\n  coord_flip() +\n  labs(\n    title = \"Weighted Average AFINN Sentiment by Topic\",\n    x = \"Topic\", \n    y = \"Average AFINN Sentiment\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"none\", \n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Weighted Average AFINN Sentiment by Topic<br>\n*Note.* Bars represent the average sentiment score for each topic, weighted by gamma (topic membership probability). The dashed line marks neutral sentiment. Differences across topics are minimal and statistically non-significant.](index_files/figure-html/fig-topic-sentiment-1.png){#fig-topic-sentiment width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# weighted regression: sentiment ~ topic (verifies non-significant differences)\nsentiment_topic_long <- meta_theta_df |>\n  select(tweet_index, sentiment_afinn, starts_with(\"topic_\")) |>\n  pivot_longer(\n    cols         = starts_with(\"topic_\"),\n    names_to     = \"topic\",\n    values_to    = \"gamma\",\n    names_prefix = \"topic_\"\n  ) |>\n  mutate(topic = factor(topic, levels = as.character(1:5)))\n\nweighted_model <- lm(sentiment_afinn ~ topic, data = sentiment_topic_long, weights = gamma)\nsummary(weighted_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = sentiment_afinn ~ topic, data = sentiment_topic_long, \n    weights = gamma)\n\nWeighted Residuals:\n    Min      1Q  Median      3Q     Max \n-9.6154 -0.8085  0.0898  0.5569  5.6288 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.843559   0.072602  11.619   <2e-16 ***\ntopic2      -0.040555   0.103362  -0.392    0.695    \ntopic3      -0.068844   0.103068  -0.668    0.504    \ntopic4      -0.042529   0.102899  -0.413    0.679    \ntopic5      -0.006947   0.102690  -0.068    0.946    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.163 on 6350 degrees of freedom\nMultiple R-squared:  9.466e-05,\tAdjusted R-squared:  -0.0005352 \nF-statistic: 0.1503 on 4 and 6350 DF,  p-value: 0.9629\n```\n\n\n:::\n:::\n\n\n## Predictors of User Engagement\n\n### Hashtag and Cashtag Features\n\nTo examine whether content packaging was associated with engagement (RQ2), mean engagement metrics were first compared by tag presence (@tbl-tag-engagement), and then three negative binomial GLMs were fitted predicting likes, replies, and retweets from hashtag presence, hashtag count, cashtag presence, and year (@tbl-tag-glm, @fig-tag-irr).\n\nDescriptively, tweets containing hashtags received slightly higher mean likes (3.11 vs. 2.89) and notably higher mean retweets (2.86 vs. 1.23), though slightly fewer replies on average (0.12 vs. 0.19). Tweets with cashtags had higher mean values on all three metrics, but the number of cashtag-containing tweets was too small (n = 22) for reliable comparison.\n\n\n::: {#tbl-tag-engagement .cell}\n\n```{.r .cell-code}\n# compute mean engagement metrics by hashtag and cashtag presence\ntag_engagement_summary <- tag_features |>\n  summarise(\n    likes_no_hashtag    = round(mean(likes_count[!has_hashtag]), 2),\n    likes_hashtag       = round(mean(likes_count[has_hashtag]), 2),\n    retweets_no_hashtag = round(mean(retweets_count[!has_hashtag]), 2),\n    retweets_hashtag    = round(mean(retweets_count[has_hashtag]), 2),\n    replies_no_hashtag  = round(mean(replies_count[!has_hashtag]), 2),\n    replies_hashtag     = round(mean(replies_count[has_hashtag]), 2),\n    likes_no_cashtag    = round(mean(likes_count[!has_cashtag]), 2),\n    likes_cashtag       = round(mean(likes_count[has_cashtag]), 2),\n    retweets_no_cashtag = round(mean(retweets_count[!has_cashtag]), 2),\n    retweets_cashtag    = round(mean(retweets_count[has_cashtag]), 2),\n    replies_no_cashtag  = round(mean(replies_count[!has_cashtag]), 2),\n    replies_cashtag     = round(mean(replies_count[has_cashtag]), 2)\n  )\n\nknitr::kable(\n  tibble(\n    Condition       = c(\"No Hashtag\", \"Hashtag\", \"No Cashtag\", \"Cashtag\"),\n    `Mean Likes`    = c(tag_engagement_summary$likes_no_hashtag,\n                        tag_engagement_summary$likes_hashtag,\n                        tag_engagement_summary$likes_no_cashtag,\n                        tag_engagement_summary$likes_cashtag),\n    `Mean Replies`  = c(tag_engagement_summary$replies_no_hashtag,\n                        tag_engagement_summary$replies_hashtag,\n                        tag_engagement_summary$replies_no_cashtag,\n                        tag_engagement_summary$replies_cashtag),\n    `Mean Retweets` = c(tag_engagement_summary$retweets_no_hashtag,\n                        tag_engagement_summary$retweets_hashtag,\n                        tag_engagement_summary$retweets_no_cashtag,\n                        tag_engagement_summary$retweets_cashtag)\n  ),\n  align = c('l', 'c', 'c', 'c'),\n  caption = \"Mean Engagement Metrics by Tag Presence\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Mean Engagement Metrics by Tag Presence\n\n|Condition  | Mean Likes | Mean Replies | Mean Retweets |\n|:----------|:----------:|:------------:|:-------------:|\n|No Hashtag |    2.89    |     0.19     |     1.23      |\n|Hashtag    |    3.11    |     0.12     |     2.86      |\n|No Cashtag |    3.04    |     0.14     |     2.35      |\n|Cashtag    |    4.05    |     0.23     |     2.41      |\n\n\n:::\n:::\n\n\n@tbl-tag-glm and @fig-tag-irr present the exponentiated regression coefficients (incident rate ratios, IRRs) from the tag-based negative binomial models. The number of hashtags per tweet was a positive predictor of all three engagement outcomes: likes (IRR = 1.08, p < .001), replies (IRR = 1.06, p = .021), and retweets (IRR = 1.13, p < .001). By contrast, simply having any hashtag at all was a negative predictor for likes (IRR = 0.60, p < .001) and replies (IRR = 0.39, p < .001) once hashtag count was included in the model, and was not significant for retweets. This pattern reflects a compositional effect: tweets with only one or two hashtags do not benefit from the discoverability that rich hashtag networks provide, whereas tweets with many hashtags tend to attract more engagement across all metrics. Cashtag presence was not significantly associated with any engagement outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# fit negative binomial GLMs for each engagement metric using tag features\ntag_glm_likes <- glm.nb(\n  likes_count ~ has_hashtag + has_cashtag + n_hashtag + year,\n  data = tag_features\n)\ntag_glm_replies <- glm.nb(\n  replies_count ~ has_hashtag + has_cashtag + n_hashtag + year,\n  data = tag_features\n)\ntag_glm_retweets <- glm.nb(\n  retweets_count ~ has_hashtag + has_cashtag + n_hashtag + year,\n  data = tag_features\n)\n\ntag_models <- list(Likes = tag_glm_likes, Replies = tag_glm_replies, Retweets = tag_glm_retweets)\n\ntag_coef_all <- bind_rows(lapply(names(tag_models), function(nm) {\n  tidy(tag_models[[nm]], exponentiate = TRUE) |>\n    filter(term != \"(Intercept)\") |>\n    mutate(\n      # Wald CIs on the log-rate scale (delta method)\n      # faster than profile-likelihood confint()\n      conf.low  = estimate * exp(-1.96 * std.error),\n      conf.high = estimate * exp( 1.96 * std.error),\n      outcome   = nm\n    )\n}))\n```\n:::\n\n\n\n::: {#tbl-tag-glm .cell}\n\n```{.r .cell-code}\n# extract and format exponentiated coefficients (IRRs) from the tag GLMs\nknitr::kable(\n  tag_coef_all |>\n    select(outcome, term, estimate, conf.low, conf.high, p.value) |>\n    mutate(\n      term = recode(term,\n        \"has_hashtagTRUE\" = \"Has Hashtag\",\n        \"has_cashtagTRUE\" = \"Has Cashtag\",\n        \"n_hashtag\"       = \"Number of Hashtags\",\n        \"year\"            = \"Year\"\n      ),\n      outcome = factor(outcome, levels = c(\"Likes\", \"Replies\", \"Retweets\"))\n    ) |>\n    rename(\n      Outcome = outcome, Predictor = term, IRR = estimate,\n      `95% CI Low` = conf.low, `95% CI High` = conf.high, `p` = p.value\n    ),\n  caption = \"Negative Binomial GLMs: Tag Features Predicting User Engagement\",\n  align = c('l', 'l', 'c', 'c', 'c', 'c'),\n  digits  = 3\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Negative Binomial GLMs: Tag Features Predicting User Engagement\n\n|Outcome  |Predictor          |  IRR  | 95% CI Low | 95% CI High |   p   |\n|:--------|:------------------|:-----:|:----------:|:-----------:|:-----:|\n|Likes    |Has Hashtag        | 0.596 |   0.474    |    0.751    | 0.000 |\n|Likes    |Has Cashtag        | 1.179 |   0.412    |    3.375    | 0.759 |\n|Likes    |Number of Hashtags | 1.081 |   1.055    |    1.108    | 0.000 |\n|Likes    |Year               | 1.239 |   1.161    |    1.322    | 0.000 |\n|Replies  |Has Hashtag        | 0.391 |   0.251    |    0.609    | 0.000 |\n|Replies  |Has Cashtag        | 1.955 |   0.303    |   12.618    | 0.481 |\n|Replies  |Number of Hashtags | 1.056 |   1.008    |    1.106    | 0.021 |\n|Replies  |Year               | 1.300 |   1.147    |    1.475    | 0.000 |\n|Retweets |Has Hashtag        | 1.023 |   0.832    |    1.258    | 0.832 |\n|Retweets |Has Cashtag        | 0.667 |   0.257    |    1.733    | 0.406 |\n|Retweets |Number of Hashtags | 1.125 |   1.102    |    1.150    | 0.000 |\n|Retweets |Year               | 1.152 |   1.088    |    1.220    | 0.000 |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IRR dot plot with 95% CIs for tag-based engagement predictors\nggplot(tag_coef_all, aes(x = estimate, y = term, color = outcome)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray60\") +\n  geom_point(size = 3, position = position_dodge(0.5)) +\n  geom_errorbarh(\n    aes(xmin = conf.low, xmax = conf.high),\n    height = 0.2, position = position_dodge(0.5)\n  ) +\n  labs(\n    title = \"Tag-Based Predictors of Tweet Engagement (IRR Plot)\",\n    x = \"Incident Rate Ratio (IRR)\", y = \"Predictor\", color = \"Outcome\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\", \n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Tag-Based Predictors of Tweet Engagement (IRR Plot)<br>\n*Note.* Points represent incident rate ratios (IRRs) and horizontal bars represent 95% confidence intervals. The dashed vertical line at IRR = 1 indicates no effect. IRR > 1 indicates a positive association with engagement.](index_files/figure-html/fig-tag-irr-1.png){#fig-tag-irr width=768}\n:::\n:::\n\n\n### Sentiment and Topic as Predictors\n\nTo directly test the associations between discourse characteristics and engagement, three negative binomial GLMs were fitted predicting likes, replies, and retweets from AFINN sentiment scores, LDA topic probabilities (Topics 1–4, with Topic 5 as the implicit baseline through the compositional constraint), and year fixed effects (@tbl-sentiment-topic-glm, @fig-topic-irr).\n\nAFINN sentiment was not a statistically significant predictor of any engagement outcome. Its IRR was 0.99 for likes (p = .676), 0.92 for replies (p = .081), and 0.98 for retweets (p = .383). This finding indicates that a more positive or more negative emotional tone alone did not reliably increase or decrease engagement once topic composition and year were taken into account.\n\nBy contrast, year was a consistent and substantial predictor of engagement. Relative to 2017, tweets from 2018 showed dramatically higher expected likes (IRR = 4.00) and replies (IRR = 8.23), and tweets from 2020 and 2021 also showed significantly higher likes and replies. Retweets were significantly higher in 2018 (IRR = 2.13) and 2021 (IRR = 2.12) relative to 2017. These large year effects suggest that the overall audience for AI content on Twitter grew substantially after 2017, leading to more engagement across the board regardless of the content's tone.\n\nTopic effects were present for some outcomes but should be interpreted carefully because LDA topic probabilities are compositional—increasing one topic's probability necessarily reduces the others. Topic 2 showed a strong negative association with likes and retweets, while Topic 4 showed a strong positive association with replies. However, some estimated IRRs were extremely large or small, indicating instability likely due to near-collinearity among topic predictors. The most defensible interpretation is that business-innovation framing (Topic 4) may be associated with more conversational engagement, while certain technology-and-market content (Topic 2) may attract less passive amplification, but these conclusions require further testing with more robust specifications.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# convert year to a factor so GLMs treat it as categorical fixed effects\nglm_data <- meta_theta_df |>\n  mutate(year = factor(year(date_utc)))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# NB GLM: AFINN sentiment + LDA topic probabilities + year predicting likes\nglm_likes <- glm.nb(\n  likes_count ~ sentiment_afinn + topic_1 + topic_2 + topic_3 + topic_4 + year,\n  data = glm_data\n)\ncat(\"=== Model: likes_count ===\\n\")\nsummary(glm_likes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Model: likes_count ===\n\nCall:\nglm.nb(formula = likes_count ~ sentiment_afinn + topic_1 + topic_2 + \n    topic_3 + topic_4 + year, data = glm_data, init.theta = 0.1753681108, \n    link = log)\n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -4.03022    2.06681  -1.950 0.051180 .  \nsentiment_afinn  0.01122    0.02750   0.408 0.683354    \ntopic_1          7.00273    3.40404   2.057 0.039669 *  \ntopic_2         20.51559    3.37578   6.077 1.22e-09 ***\ntopic_3          0.97862    3.64066   0.269 0.788082    \ntopic_4         -7.01853    3.61877  -1.939 0.052443 .  \nyear2018         1.23738    0.24369   5.078 3.82e-07 ***\nyear2019         0.79655    0.24130   3.301 0.000963 ***\nyear2020         1.08923    0.24018   4.535 5.76e-06 ***\nyear2021         1.85646    0.24253   7.655 1.94e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.1709) family taken to be 1)\n\n    Null deviance: 1067.2  on 1270  degrees of freedom\nResidual deviance: 1040.5  on 1261  degrees of freedom\nAIC: 4683.8\n\nNumber of Fisher Scoring iterations: 25\n\n              Theta:  0.17537 \n          Std. Err.:  0.00926 \nWarning while fitting theta: alternation limit reached \n\n 2 x log-likelihood:  -4661.79500 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# same model structure predicting reply counts\nglm_replies <- glm.nb(\n  replies_count ~ sentiment_afinn + topic_1 + topic_2 + topic_3 + topic_4 + year,\n  data = glm_data\n)\ncat(\"=== Model: replies_count ===\\n\")\nsummary(glm_replies)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Model: replies_count ===\n\nCall:\nglm.nb(formula = replies_count ~ sentiment_afinn + topic_1 + \n    topic_2 + topic_3 + topic_4 + year, data = glm_data, init.theta = 0.1012493424, \n    link = log)\n\nCoefficients:\n                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      -4.62931    3.45547  -1.340 0.180341    \nsentiment_afinn  -0.10863    0.04545  -2.390 0.016845 *  \ntopic_1          17.98263    5.46880   3.288 0.001008 ** \ntopic_2           2.85307    5.53684   0.515 0.606352    \ntopic_3         -13.98182    6.23073  -2.244 0.024832 *  \ntopic_4          -0.54360    6.05105  -0.090 0.928418    \nyear2018          2.00539    0.50254   3.991 6.59e-05 ***\nyear2019          0.94486    0.52320   1.806 0.070929 .  \nyear2020          1.66313    0.50513   3.293 0.000993 ***\nyear2021          2.07555    0.50109   4.142 3.44e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.1012) family taken to be 1)\n\n    Null deviance: 423.43  on 1270  degrees of freedom\nResidual deviance: 344.67  on 1261  degrees of freedom\nAIC: 1054.4\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.1012 \n          Std. Err.:  0.0152 \n\n 2 x log-likelihood:  -1032.3900 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# same model structure predicting retweet counts\nglm_retweets <- glm.nb(\n  retweets_count ~ sentiment_afinn + topic_1 + topic_2 + topic_3 + topic_4 + year,\n  data = glm_data\n)\ncat(\"=== Model: retweets_count ===\\n\")\nsummary(glm_retweets)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== Model: retweets_count ===\n\nCall:\nglm.nb(formula = retweets_count ~ sentiment_afinn + topic_1 + \n    topic_2 + topic_3 + topic_4 + year, data = glm_data, init.theta = 0.2623757604, \n    link = log)\n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -3.71255    1.76175  -2.107 0.035091 *  \nsentiment_afinn -0.03267    0.02310  -1.414 0.157233    \ntopic_1          8.58860    2.88372   2.978 0.002898 ** \ntopic_2         16.85582    2.82445   5.968  2.4e-09 ***\ntopic_3         -9.15645    3.05451  -2.998 0.002720 ** \ntopic_4          4.39220    3.06705   1.432 0.152126    \nyear2018         0.55233    0.20127   2.744 0.006067 ** \nyear2019        -0.14420    0.20106  -0.717 0.473249    \nyear2020         0.31611    0.19868   1.591 0.111609    \nyear2021         0.74616    0.19952   3.740 0.000184 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(0.2624) family taken to be 1)\n\n    Null deviance: 1218.6  on 1270  degrees of freedom\nResidual deviance: 1071.3  on 1261  degrees of freedom\nAIC: 4313.1\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  0.2624 \n          Std. Err.:  0.0150 \n\n 2 x log-likelihood:  -4291.0870 \n```\n\n\n:::\n:::\n\n\n\n::: {#tbl-sentiment-topic-glm .cell}\n\n```{.r .cell-code}\nmodels_list <- list(Likes = glm_likes, Replies = glm_replies, Retweets = glm_retweets)\n\ncoef_all <- bind_rows(lapply(names(models_list), function(nm) {\n  tidy(models_list[[nm]], exponentiate = TRUE) |>\n    # drop intercept and year fixed effects; \n    # table shows only content predictors\n    filter(!grepl(\"Intercept|^year\", term)) |>\n    mutate(\n      conf.low  = estimate * exp(-1.96 * std.error),\n      conf.high = estimate * exp( 1.96 * std.error),\n      outcome   = nm\n    )\n}))\n\nknitr::kable(\n  coef_all |>\n    select(outcome, term, estimate, conf.low, conf.high, p.value) |>\n    mutate(\n      term = recode(term,\n        \"sentiment_afinn\" = \"AFINN Sentiment\",\n        \"topic_1\" = \"Topic 1\", \"topic_2\" = \"Topic 2\",\n        \"topic_3\" = \"Topic 3\", \"topic_4\" = \"Topic 4\"\n      )\n    ) |>\n    rename(\n      Outcome = outcome, Predictor = term, IRR = estimate,\n      `95% CI Low` = conf.low, `95% CI High` = conf.high, `p` = p.value\n    ),\n  align = c('l', 'l', 'c', 'c', 'c', 'c'),\n  caption = \"Negative Binomial GLMs: Sentiment and Topics Predicting User Engagement (Year Fixed Effects Excluded)\",\n  digits  = 3\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Negative Binomial GLMs: Sentiment and Topics Predicting User Engagement (Year Fixed Effects Excluded)\n\n|Outcome  |Predictor       |     IRR      | 95% CI Low  | 95% CI High  |   p   |\n|:--------|:---------------|:------------:|:-----------:|:------------:|:-----:|\n|Likes    |AFINN Sentiment | 1.011000e+00 |    0.958    | 1.067000e+00 | 0.683 |\n|Likes    |Topic 1         | 1.099627e+03 |    1.392    | 8.685993e+05 | 0.040 |\n|Likes    |Topic 2         | 8.124686e+08 | 1087133.402 | 6.071980e+11 | 0.000 |\n|Likes    |Topic 3         | 2.661000e+00 |    0.002    | 3.341967e+03 | 0.788 |\n|Likes    |Topic 4         | 1.000000e-03 |    0.000    | 1.077000e+00 | 0.052 |\n|Replies  |AFINN Sentiment | 8.970000e-01 |    0.821    | 9.810000e-01 | 0.017 |\n|Replies  |Topic 1         | 6.452939e+07 |  1427.661   | 2.916687e+12 | 0.001 |\n|Replies  |Topic 2         | 1.734100e+01 |    0.000    | 8.956269e+05 | 0.606 |\n|Replies  |Topic 3         | 0.000000e+00 |    0.000    | 1.700000e-01 | 0.025 |\n|Replies  |Topic 4         | 5.810000e-01 |    0.000    | 8.216263e+04 | 0.928 |\n|Retweets |AFINN Sentiment | 9.680000e-01 |    0.925    | 1.013000e+00 | 0.157 |\n|Retweets |Topic 1         | 5.370114e+03 |   18.850    | 1.529887e+06 | 0.003 |\n|Retweets |Topic 2         | 2.091166e+07 |  82446.484  | 5.304018e+09 | 0.000 |\n|Retweets |Topic 3         | 0.000000e+00 |    0.000    | 4.200000e-02 | 0.003 |\n|Retweets |Topic 4         | 8.081800e+01 |    0.198    | 3.297828e+04 | 0.152 |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# IRR dot plot for sentiment and topic predictors (year fixed effects excluded)\nggplot(coef_all, aes(x = estimate, y = term, color = outcome)) +\n  geom_vline(xintercept = 1, linetype = \"dashed\", color = \"gray60\") +\n  geom_point(size = 3, position = position_dodge(0.5)) +\n  geom_errorbarh(\n    aes(xmin = conf.low, xmax = conf.high),\n    height = 0.2, position = position_dodge(0.5)\n  ) +\n  labs(\n    title = \"Sentiment and Topic Predictors of Tweet Engagement (IRR Plot)\",\n    x = \"Incident Rate Ratio (IRR)\", y = \"Predictor\", color = \"Outcome\"\n  ) +\n  theme_minimal() +\n  theme(\n    legend.position = \"bottom\", \n    plot.title = element_text(hjust = 0.5)\n  )\n```\n\n::: {.cell-output-display}\n![Sentiment and Topic Predictors of Tweet Engagement (IRR Plot)<br>\n*Note.* Points represent incident rate ratios (IRRs) and horizontal bars represent 95% confidence intervals. The dashed vertical line at IRR = 1 indicates no effect. Year fixed effects are excluded from the plot for clarity.](index_files/figure-html/fig-topic-irr-1.png){#fig-topic-irr width=768}\n:::\n:::\n\n\n# Discussion & Conclusion\n\n## Discussion\n\nTaken together, the results provide partial support for both research questions while revealing important nuances in how AI discourse evolved and how it connected to audience engagement on Twitter between 2017 and 2021.\n\n### Thematic Stability with Gradual Specialization (RQ1)\n\nFor RQ1, the LDA topic modeling results indicate that AI discourse on Twitter did not undergo a dramatic thematic transformation during the study period. Instead, the corpus showed a relatively stable thematic structure built around five recurring clusters: robotics and automation, technology and markets, data science and security, business and innovation, and applied AI ecosystem vocabulary. The near-constant average topic probabilities across all years (all close to 0.20) suggest a diverse but consistently balanced conversation that absorbed new developments without being reorganized by them.\n\nThis finding may appear surprising given that 2017 to 2021 saw substantial milestones in AI, including major advances in natural language processing, growing public debate about AI ethics, and the commercialization of generative AI tools. One explanation is that the keyword-based sampling strategy (\"Artificial Intelligence\") may have overrepresented promotional, institutional, and hashtag-driven content, which tends to revolve around a stable set of industry frames regardless of specific technological developments. A corpus built around event-specific terms or date-anchored keywords might reveal sharper thematic shifts.\n\nDespite the overall thematic stability, the hashtag analysis provided a more nuanced story about discursive evolution. While #artificialintelligence and #ai dominated in every year, the lower-ranked hashtags shifted gradually toward more specialized terms such as #machinelearning, #datascience, and #deeplearning, while broader infrastructure terms like #bigdata and #iot declined in relative prominence. This pattern suggests that AI discourse on Twitter evolved less through wholesale topical replacement and more through increasing specificity, and users began categorizing their AI discussions into more precise technical subfields rather than relying solely on the broad \"artificial intelligence\" framing.\n\nThe sentiment trend reinforced and sharpened this picture. The steady increase in mean AFINN sentiment from 0.33 in 2017 to 1.11 in 2021 indicates that public AI discourse became progressively more positive over the five years. This is consistent with the broader narrative of AI mainstreaming, in which the technology became increasingly framed as a source of opportunity, economic value, and practical innovation rather than as an abstract, uncertain, or threatening technological force. Critically, sentiment did not differ meaningfully across topics, where the slight gap between the most positive (Topic 4: 0.84) and least positive (Topic 5: 0.79) topics was not statistically significant. This indicates that optimism about AI was a property of the time period in which a tweet was posted, not of the specific thematic cluster it belonged to.\n\n### Engagement Patterns and the Role of Context (RQ2)\n\nFor RQ2, the most consistent finding was that user engagement was shaped more strongly by historical context than by the specific tone or topic of individual tweets. Year was a robust predictor across all three engagement models: tweets from 2018 showed dramatically higher expected likes (IRR = 4.00) and replies (IRR = 8.23) compared to those from 2017, and elevated engagement persisted through 2020 and 2021 for likes and replies, and through 2021 for retweets. This pattern suggests that as AI became a more mainstream cultural and economic topic in subsequent years, the Twitter audience for AI content grew larger and more active.\n\nSentiment, by contrast, was not a significant predictor of engagement once year and topic composition were included in the model. The IRRs for AFINN sentiment were close to 1.00 across all three outcomes and did not reach statistical significance. For content creators and communications practitioners, this is an important finding: crafting more enthusiastic or more alarmist AI content did not appear to translate automatically into greater audience engagement, at least within the context of this corpus. Instead, engagement was tied more to the broader social and platform context in which content was posted.\n\nThe hashtag analysis added a more actionable finding to the engagement story. The number of hashtags per tweet was consistently and positively associated with all three engagement metrics in the regression models, while simple hashtag presence (just having at least one hashtag) was negatively associated with likes and replies once hashtag count was controlled. This compositional pattern suggests that richly tagged tweets tend to situate content within multiple streams of existing attention, making them more discoverable and more likely to be engaged with. In contrast, a minimal or token use of hashtags does not reliably confer these discoverability benefits. This is a more specific finding than a simple \"use hashtags\" recommendation and suggests that the density of hashtagging matters.\n\nTopic effects on engagement were present in some models but were difficult to interpret cleanly due to the compositional nature of LDA topic probabilities, which creates near-multicollinearity among topic predictors and produces inflated or unstable coefficient estimates. The tentative pattern — with business-innovation framing (Topic 4) associated with more conversational replies, and technology-market framing (Topic 2) associated with less passive amplification — is theoretically plausible. Business- and future-oriented AI language may invite debate and personal response, while more abstract technology-market language may be shared and amplified less. However, these conclusions require more stable model specifications before they can be stated with confidence.\n\nCashtags were too rare (only 22 tweets) to support any strong engagement claims. Their near-absence confirms that financial-sector AI discussion was peripheral in this corpus, even if a small number of tweets connected AI talk to cryptocurrency or stock market speculation.\n\n## Limitations\n\nSeveral limitations qualify these conclusions. First, the analysis used a stratified sample of 3,000 tweets from a corpus of over 893,000 observations, so subtle yearly thematic changes may have been dampened by reduced statistical power. Second, the data were collected using the keyword \"Artificial Intelligence,\" which may overrepresent institutional, promotional, and professionally framed content while underrepresenting informal, critical, or personal AI discussions. Third, lexicon-based sentiment analysis cannot detect sarcasm, mixed sentiment, or context-dependent irony, which are common in social media writing. Fourth, the LDA topic model was sensitive to the broad shared vocabulary in the corpus, which may explain why yearly topic averages remained so similar across years.\n\n## Future Directions\n\nFuture research could address these limitations in several ways. Structural topic modeling (STM), which explicitly models topic prevalence as a function of metadata variables such as year or engagement level, could yield more sensitive estimates of thematic change and its relationship to engagement. Using larger yearly strata or the full corpus would provide greater statistical power to detect subtle shifts in AI discourse. Integrating sentence-level or contextual sentiment models, such as transformer-based classifiers trained on social media data, could capture the nuanced and ironic tone of tweets more validly than word-level dictionaries. Finally, future work could examine specific AI milestones (such as the release of GPT-3 in 2020) as natural experiments to test whether particular events produced detectable shifts in the themes or sentiment of AI discourse on Twitter.\n\n## Conclusion\n\nThis study finds that AI discourse on Twitter became steadily more positive and increasingly engaging between 2017 and 2021, without a fundamental reorganization of its underlying thematic structure. The evidence suggests that public AI discourse evolved through two primary mechanisms: increasing technical specialization, as users began labeling their tweets with more precise applied subfield hashtags, and growing optimism, as AI became more integrated into business and everyday technology conversation. Engagement with AI content was driven more by the growing public interest in AI over time than by the specific emotional tone or thematic focus of individual tweets. These findings contribute to a broader understanding of how transformative technologies are discursively normalized and adopted within public social media spaces.\n\n# References {.unnumbered}\n\n::: {#refs}\n:::\n\n# Appendix {.unnumbered}\n\n**Narrowing Process.** The original dataset was filtered to retain only English-language original tweets (excluding retweets), reducing the corpus to a smaller subset. Equal-allocation stratified random sampling by posting year (N = 600 per year × 5 years = 3,000) was then applied to ensure temporal balance while maintaining computational efficiency. See the code in the [Data > Observations](#observations) section.\n\n**UTC Conversion Process.** The original `created_at` variable was stored as a character string with an Eastern Time suffix. It was parsed to a calendar-time object using `ymd_hms()` with `tz = \"America/New_York\"`, then converted to UTC using `with_tz()`, and finally coerced to a `Date` object stored as `date_utc`. See the code in the [Data > Variables](#variables) section.\n\n**Separation Process.** Hashtags and cashtags in the dataset were stored as Python-style list strings (e.g., `\"['ai', 'ml']\"`). To obtain single tokens, bracket and quote characters were removed with `str_remove_all()`, and the resulting comma-separated strings were split into individual rows using `separate_rows()`. See the code in the [Data > Text Variables > Hashtags](#hashtags) sections.\n\n# Environment & Version {.unnumbered}\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"R version:\", R.version.string, \"\\n\\n\")\npkgs <- c(\"MASS\", \"tidyverse\", \"tidytext\", \"textdata\", \"topicmodels\",\n          \"scales\", \"broom\", \"textutils\", \"knitr\")\npkg_versions <- data.frame(\n  Package = pkgs,\n  Version = sapply(pkgs, function(p) as.character(packageVersion(p)))\n)\nknitr::kable(pkg_versions, row.names = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version: R version 4.5.2 (2025-10-31) \n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|Package     |Version |\n|:-----------|:-------|\n|MASS        |7.3.65  |\n|tidyverse   |2.0.0   |\n|tidytext    |0.4.3   |\n|textdata    |0.4.5   |\n|topicmodels |0.2.17  |\n|scales      |1.4.0   |\n|broom       |1.0.12  |\n|textutils   |0.4.3   |\n|knitr       |1.51    |\n\n\n:::\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}