#!/usr/bin/env python3
"""Sync the change-log timeline from Notion into en/changes/_timeline.md.

Reads the "Site Change Log" Notion database (one row per timeline node,
Type = Phase | Entry; entry detail bullets live in the row's page body)
and regenerates the markdown partial consumed by
src/filters/changelog-timeline.lua.

Usage:
    NOTION_TOKEN=ntn_... python3 scripts/sync-changelog.py [--strict]

Config:
    NOTION_TOKEN         integration token (required; never commit it)
    NOTION_CHANGELOG_DB  database id (optional; falls back to
                         scripts/notion-changelog.json {"database_id": ...})

Behavior:
    - stdlib only; no third-party packages
    - graceful degrade: missing token/config or any network error prints a
      warning and exits 0, keeping the existing _timeline.md, so builds
      work offline. --strict turns those cases into exit 1.
    - writes only if content changed (atomic replace), so repeated runs
      don't churn file mtimes.

API note: pinned to Notion-Version 2022-06-28 (classic database endpoints).
Newer API versions (2025-09+) replace databases/{id}/query with
data-source queries; revisit if the pin ever stops working.
"""

import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_FILE = REPO_ROOT / "en" / "changes" / "_timeline.md"
CONFIG_FILE = REPO_ROOT / "scripts" / "notion-changelog.json"

API_BASE = "https://api.notion.com/v1"
NOTION_VERSION = "2022-06-28"
TIMEOUT = 15
BLOCK_FETCH_DELAY = 0.35  # stay under Notion's ~3 req/s limit

HEADER_COMMENT = (
    "<!-- Generated by scripts/sync-changelog.py from Notion"
    " — do not edit by hand. -->"
)


class SyncSkip(Exception):
    """Non-fatal condition: keep the existing file."""


def warn(msg):
    print(f"warning: {msg}", file=sys.stderr)


# ---------------------------------------------------------------------------
# Notion API
# ---------------------------------------------------------------------------

def notion_request(token, method, url, payload=None, retried=False):
    data = json.dumps(payload).encode() if payload is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Notion-Version", NOTION_VERSION)
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return json.load(resp)
    except urllib.error.HTTPError as e:
        if e.code == 429 and not retried:
            time.sleep(float(e.headers.get("Retry-After", 1)))
            return notion_request(token, method, url, payload, retried=True)
        raise SyncSkip(f"Notion API HTTP {e.code} for {url}") from e
    except (urllib.error.URLError, TimeoutError, OSError) as e:
        raise SyncSkip(f"network error: {e}") from e


def query_database(token, db_id):
    rows = []
    payload = {"page_size": 100}
    while True:
        data = notion_request(
            token, "POST", f"{API_BASE}/databases/{db_id}/query", payload
        )
        rows.extend(data.get("results", []))
        if not data.get("has_more"):
            return rows
        payload["start_cursor"] = data["next_cursor"]


def fetch_bullets(token, page_id):
    """Return the rich-text arrays of the page's bulleted list items."""
    bullets = []
    url = f"{API_BASE}/blocks/{page_id}/children?page_size=100"
    while True:
        data = notion_request(token, "GET", url)
        for block in data.get("results", []):
            btype = block.get("type")
            if btype == "bulleted_list_item":
                bullets.append(block[btype].get("rich_text", []))
            else:
                warn(f"skipping non-bullet block '{btype}' on page {page_id}")
        if not data.get("has_more"):
            return bullets
        url = (
            f"{API_BASE}/blocks/{page_id}/children"
            f"?page_size=100&start_cursor={data['next_cursor']}"
        )


# ---------------------------------------------------------------------------
# Property extractors
# ---------------------------------------------------------------------------

def _prop(page, name):
    return page.get("properties", {}).get(name, {})


def prop_title(page, name):
    return "".join(s.get("plain_text", "") for s in _prop(page, name).get("title", []))


def prop_rich(page, name):
    return _prop(page, name).get("rich_text", [])


def prop_text(page, name):
    return "".join(s.get("plain_text", "") for s in prop_rich(page, name))


def prop_number(page, name):
    return _prop(page, name).get("number")


def prop_select(page, name):
    sel = _prop(page, name).get("select")
    return sel.get("name") if sel else None


def prop_date(page, name):
    d = _prop(page, name).get("date")
    return d.get("start") if d else None


# ---------------------------------------------------------------------------
# Rich text -> markdown
# ---------------------------------------------------------------------------

def escape_md(text):
    out = []
    for i, ch in enumerate(text):
        if ch in "\\`*_":
            out.append("\\" + ch)
        elif ch == "<":
            out.append("\\<")
        elif ch == "{" and i == 0:
            out.append("\\{")
        else:
            out.append(ch)
    return "".join(out)


def rich_text_to_md(spans):
    parts = []
    for span in spans:
        text = span.get("plain_text", "")
        ann = span.get("annotations", {})
        for unsupported in ("strikethrough", "underline"):
            if ann.get(unsupported):
                warn(f"{unsupported} annotation degraded to plain text: {text!r}")
        if span.get("href"):
            warn(f"link degraded to plain text: {text!r}")
        if ann.get("code"):
            if "`" in text:
                parts.append(f"`` {text} ``")
            else:
                parts.append(f"`{text}`")
        elif ann.get("bold"):
            parts.append(f"**{escape_md(text)}**")
        elif ann.get("italic"):
            parts.append(f"*{escape_md(text)}*")
        else:
            parts.append(escape_md(text))
    return "".join(parts)


def attr_escape(s):
    return s.replace('"', '\\"')


def fmt_num(x):
    if x is None:
        return "0"
    return f"{x:g}"


# ---------------------------------------------------------------------------
# Markdown generation
# ---------------------------------------------------------------------------

def render_markdown(token, rows):
    def sort_key(page):
        start = prop_date(page, "Start") or "9999-12-31"
        is_entry = 1 if prop_select(page, "Type") == "Entry" else 0
        return (start, is_entry)

    lines = [HEADER_COMMENT, ""]
    for page in sorted(rows, key=sort_key):
        ptype = prop_select(page, "Type")
        name = rich_text_to_md(_prop(page, "Name").get("title", []))

        if ptype == "Phase":
            lines.append(f'## {name} {{range="{attr_escape(prop_text(page, "Date label"))}"}}')
            lines.append("")
        elif ptype == "Entry":
            attrs = " ".join(
                f'{k}="{attr_escape(v)}"'
                for k, v in [
                    ("date", prop_text(page, "Date label")),
                    ("iso", prop_date(page, "Start") or ""),
                    ("commits", fmt_num(prop_number(page, "Commits"))),
                    ("hours", fmt_num(prop_number(page, "Hours"))),
                    ("days", fmt_num(prop_number(page, "Days"))),
                ]
            )
            lines.append(f"### {name} {{{attrs}}}")
            lines.append("")
            summary = rich_text_to_md(prop_rich(page, "Summary"))
            if summary:
                lines.append(summary)
                lines.append("")
            time.sleep(BLOCK_FETCH_DELAY)
            bullets = fetch_bullets(token, page["id"])
            if bullets:
                for spans in bullets:
                    lines.append(f"- {rich_text_to_md(spans)}")
                lines.append("")
        else:
            warn(f"row with unknown Type {ptype!r} skipped: {name!r}")
    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    strict = "--strict" in sys.argv[1:]

    def bail(msg):
        warn(f"{msg}; keeping existing {OUT_FILE.relative_to(REPO_ROOT)}")
        sys.exit(1 if strict else 0)

    token = os.environ.get("NOTION_TOKEN")
    if not token:
        bail("NOTION_TOKEN not set")

    db_id = os.environ.get("NOTION_CHANGELOG_DB")
    if not db_id and CONFIG_FILE.exists():
        try:
            db_id = json.loads(CONFIG_FILE.read_text()).get("database_id")
        except (json.JSONDecodeError, OSError) as e:
            bail(f"cannot read {CONFIG_FILE.name}: {e}")
    if not db_id:
        bail("no database id (NOTION_CHANGELOG_DB or scripts/notion-changelog.json)")

    try:
        rows = query_database(token, db_id)
        content = render_markdown(token, rows)
    except SyncSkip as e:
        bail(str(e))

    if OUT_FILE.exists() and OUT_FILE.read_text() == content:
        print(f"unchanged: {OUT_FILE.relative_to(REPO_ROOT)}")
        return

    tmp = OUT_FILE.with_suffix(".md.tmp")
    tmp.write_text(content)
    os.replace(tmp, OUT_FILE)
    print(f"wrote {OUT_FILE.relative_to(REPO_ROOT)} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
